# Generated by Django 5.2 on 2026-04-09 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timed_out', 'Timed Out')], default='pending', max_length=20)),
                ('preferred_executor', models.CharField(choices=[('codex', 'Codex'), ('claude', 'Claude')], default='codex', max_length=20)),
                ('selected_executor', models.CharField(blank=True, choices=[('codex', 'Codex'), ('claude', 'Claude')], default='', max_length=20)),
                ('input_payload', models.JSONField()),
                ('result_payload', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('requested_by_app', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'llm_gateway_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMRunEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='llm_gateway.llmrun')),
            ],
            options={
                'db_table': 'llm_gateway_run_event',
                'ordering': ['sequence', 'id'],
                'indexes': [models.Index(fields=['run', 'sequence'], name='llm_gateway_run_id_1ed821_idx'), models.Index(fields=['event_type'], name='llm_gateway_event_t_58efe9_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'sequence'), name='llm_gateway_run_event_unique_sequence')],
            },
        ),
    ]
