# Generated by Django 5.2 on 2025-09-25 03:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_initial_data'),
        ('tenants', '0001_initial'),
        ('users', '0002_passwordresettoken_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuserprofile',
            name='points_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='积分倍数'),
        ),
        migrations.AddIndex(
            model_name='tenantuserpoints',
            index=models.Index(fields=['tenant_user_profile', 'created_at'], name='idx_tenant_user_points_profile'),
        ),
        migrations.AddIndex(
            model_name='tenantuserpoints',
            index=models.Index(fields=['tenant', 'member', 'created_at'], name='tup_tenant_member'),
        ),
        migrations.AddIndex(
            model_name='tenantuserpoints',
            index=models.Index(fields=['tenant', 'point_type', 'category'], name='idx_tenant_user_points_type'),
        ),
        migrations.AddIndex(
            model_name='tenantuserpoints',
            index=models.Index(condition=models.Q(('expires_at__isnull', False), ('status', 'active')), fields=['tenant', 'expires_at'], name='tup_expires'),
        ),
        migrations.AddIndex(
            model_name='tenantuserpoints',
            index=models.Index(condition=models.Q(('source_id__isnull', False)), fields=['tenant', 'source_type', 'source_id'], name='idx_tenant_user_points_source'),
        ),
        migrations.AddIndex(
            model_name='tenantusertypetag',
            index=models.Index(fields=['tenant_user_profile', 'is_active'], name='tutt_profile'),
        ),
        migrations.AddIndex(
            model_name='tenantusertypetag',
            index=models.Index(fields=['tenant', 'member', 'is_active'], name='tutt_tenant_member'),
        ),
        migrations.AddIndex(
            model_name='tenantusertypetag',
            index=models.Index(condition=models.Q(('expires_at__isnull', False), ('is_active', True)), fields=['tenant', 'expires_at'], name='tutt_expires'),
        ),
        migrations.AddIndex(
            model_name='tenantusertypetag',
            index=models.Index(condition=models.Q(('payment_id__isnull', False)), fields=['payment_id'], name='tutt_payment'),
        ),
        migrations.AddIndex(
            model_name='tenantusertypetag',
            index=models.Index(condition=models.Q(('auto_renewal', True), ('is_active', True)), fields=['tenant', 'auto_renewal', 'expires_at'], name='tutt_renewal'),
        ),
    ]
