# Generated by Django 5.2 on 2026-03-23 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_alter_tenantuserprofile_points_multiplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuserpoints',
            name='points',
            field=models.IntegerField(verbose_name='积分Change数量'),
        ),
        migrations.AlterField(
            model_name='tenantuserprofile',
            name='current_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='points.userlevel', verbose_name='current等级'),
        ),
        migrations.AlterField(
            model_name='tenantuserprofile',
            name='last_points_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后积分Change时间'),
        ),
    ]
