# Generated by Django 5.2 on 2025-10-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresettoken_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='max_trial_licenses',
            field=models.PositiveIntegerField(default=1, help_text='该用户最多可以同时持有的试用许可证数量', verbose_name='试用许可证配额'),
        ),
    ]
