# Generated by Django 5.2 on 2025-10-31 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_max_trial_licenses_to_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='max_trial_licenses',
        ),
    ]
