# Generated by Django 5.2 on 2025-06-15 08:23

from django.db import migrations


def cleanup_user_table(apps, schema_editor):
    """
    从User表中删除已迁移到Member表的普通成员
    """
    # 获取模型类
    User = apps.get_model('users', 'User')
    Member = apps.get_model('users', 'Member')
    
    # 获取所有已迁移到Member表的用户ID
    member_ids = Member.objects.values_list('id', flat=True)
    
    # 从User表中删除这些用户
    User.objects.filter(id__in=member_ids).delete()
    
    # 移除User模型中的parent字段关联
    for user in User.objects.all():
        if user.parent_id:
            user.parent = None
            user.save(update_fields=['parent'])


def reverse_cleanup(apps, schema_editor):
    """
    回滚清理操作是不可能的，因为数据已经被删除
    这里我们只能记录一条警告
    """
    print("警告：无法回滚清理操作，因为数据已经被删除")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_migrate_member_data'),
    ]

    operations = [
        migrations.RunPython(cleanup_user_table, reverse_cleanup),
        migrations.RemoveField(
            model_name='user',
            name='parent',
        ),
    ]
