# Generated by Django 5.2 on 2025-06-16 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_password_reset_token'),
        ('users', '0005_cleanup_user_model'),
    ]

    operations = [
    ]
