# Generated by Django 5.2 on 2025-07-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_member_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='wechat_id',
            field=models.CharField(blank=True, help_text='用户的微信号', max_length=32, null=True, verbose_name='微信号'),
        ),
        migrations.AddField(
            model_name='user',
            name='wechat_id',
            field=models.CharField(blank=True, help_text='用户的微信号', max_length=32, null=True, verbose_name='微信号'),
        ),
    ]
