# Generated by Django 5.2 on 2025-11-21 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_alter_tenantquota_current_storage_used_mb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('name', models.CharField(help_text='应用的显示名称', max_length=100, verbose_name='应用名称')),
                ('code', models.CharField(help_text='应用的唯一标识符（租户内唯一）', max_length=50, verbose_name='应用代码')),
                ('description', models.TextField(blank=True, verbose_name='应用描述')),
                ('logo', models.ImageField(blank=True, help_text='应用Logo图标', null=True, upload_to='applications/logos/%Y/%m/', verbose_name='Logo')),
                ('website', models.URLField(blank=True, help_text='应用官方网站', null=True, verbose_name='官网')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='联系邮箱')),
                ('current_version', models.CharField(blank=True, help_text='当前发布的版本号，如: v1.2.3', max_length=50, null=True, verbose_name='当前版本')),
                ('owner', models.CharField(blank=True, help_text='应用负责人姓名', max_length=100, verbose_name='负责人')),
                ('team', models.CharField(blank=True, help_text='开发团队名称', max_length=200, verbose_name='开发团队')),
                ('status', models.CharField(choices=[('development', '开发中'), ('testing', '测试中'), ('active', '运行中'), ('maintenance', '维护中'), ('deprecated', '已弃用'), ('archived', '已归档')], db_index=True, default='active', max_length=20, verbose_name='状态')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用该应用', verbose_name='启用')),
                ('tags', models.JSONField(blank=True, default=list, help_text='应用标签列表，用于分类和搜索', verbose_name='标签')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='其他自定义元数据', verbose_name='元数据')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '应用',
                'verbose_name_plural': '应用',
                'db_table': 'app_application',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('version', models.CharField(help_text='版本号，如: 1.0.0, 2.1.3-beta', max_length=50, verbose_name='版本号')),
                ('version_code', models.IntegerField(default=0, help_text='整数版本号，用于版本比较，如: 100, 203', verbose_name='版本代码')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('release_notes', models.TextField(blank=True, help_text='更新日志、新特性说明等', verbose_name='版本说明')),
                ('is_stable', models.BooleanField(default=True, help_text='是否为稳定版本（非beta/alpha）', verbose_name='稳定版')),
                ('is_active', models.BooleanField(default=True, help_text='是否可用', verbose_name='启用')),
                ('download_url', models.URLField(blank=True, help_text='版本下载地址', null=True, verbose_name='下载链接')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='applications.application', verbose_name='关联应用')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '应用版本',
                'verbose_name_plural': '应用版本',
                'db_table': 'app_version',
                'ordering': ['-version_code', '-release_date'],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['tenant', 'code'], name='app_applica_tenant__654d9c_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['tenant', 'status'], name='app_applica_tenant__48a60b_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['tenant', 'is_active'], name='app_applica_tenant__a30701_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='applicationversion',
            index=models.Index(fields=['application', 'version_code'], name='app_version_applica_d2e76c_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationversion',
            index=models.Index(fields=['application', 'is_active'], name='app_version_applica_c3a91c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationversion',
            unique_together={('application', 'version')},
        ),
    ]
