# Generated by Django 5.2 on 2025-11-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('feedbacks', '0004_remove_feedback_application_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='current_version',
            field=models.CharField(blank=True, default='1.0.0', help_text='当前发布的版本号，如: v1.2.3', max_length=50, verbose_name='当前版本'),
        ),
        migrations.DeleteModel(
            name='ApplicationVersion',
        ),
    ]
