# Generated by Django 5.2 on 2025-11-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_current_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='logo',
            field=models.URLField(blank=True, help_text='应用Logo地址（可使用CDN或OSS链接）', max_length=255, null=True, verbose_name='Logo'),
        ),
    ]
