# Generated by Django 5.2 on 2025-11-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='logo',
            field=models.CharField(blank=True, help_text='应用Logo地址（可使用CDN或OSS链接）', max_length=255, null=True, verbose_name='Logo'),
        ),
    ]
