# Generated by Django 5.2 on 2025-10-28 09:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0005_add_is_pinned_to_category'),
        ('tenants', '0002_alter_tenantquota_current_storage_used_mb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='收藏时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='cms.article', verbose_name='文章')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_favorites', to='tenants.tenant', verbose_name='所属租户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_favorites', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '文章收藏',
                'verbose_name_plural': '文章收藏',
                'db_table': 'interactions_article_favorite',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='interaction_user_id_18d6cc_idx'), models.Index(fields=['article'], name='interaction_article_227fdc_idx'), models.Index(fields=['tenant', 'user'], name='interaction_tenant__669bd1_idx'), models.Index(fields=['tenant', 'article'], name='interaction_tenant__7dc843_idx')],
                'unique_together': {('user', 'article')},
            },
        ),
    ]
