# Generated by Django 5.2 on 2025-10-31 13:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
        ('tenants', '0002_alter_tenantquota_current_storage_used_mb'),
        ('users', '0004_remove_member_max_trial_licenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='关注时间')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to='users.member', verbose_name='关注者')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_set', to='users.member', verbose_name='被关注者')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_follows', to='tenants.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '用户关注',
                'verbose_name_plural': '用户关注',
                'db_table': 'interactions_member_follow',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['follower', 'created_at'], name='interaction_followe_e22008_idx'), models.Index(fields=['following', 'created_at'], name='interaction_followi_2ba104_idx'), models.Index(fields=['tenant', 'follower'], name='interaction_tenant__5a8e25_idx'), models.Index(fields=['tenant', 'following'], name='interaction_tenant__5029fe_idx')],
                'unique_together': {('follower', 'following')},
            },
        ),
        migrations.CreateModel(
            name='MemberLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='点赞时间')),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_likes', to='users.member', verbose_name='点赞发起者')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_likes', to='tenants.tenant', verbose_name='所属租户')),
                ('to_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_likes', to='users.member', verbose_name='被点赞用户')),
            ],
            options={
                'verbose_name': '用户点赞',
                'verbose_name_plural': '用户点赞',
                'db_table': 'interactions_member_like',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['from_member', 'created_at'], name='interaction_from_me_3040b3_idx'), models.Index(fields=['to_member', 'created_at'], name='interaction_to_memb_8fac76_idx'), models.Index(fields=['tenant', 'from_member'], name='interaction_tenant__2dfabe_idx'), models.Index(fields=['tenant', 'to_member'], name='interaction_tenant__d58f37_idx')],
                'unique_together': {('from_member', 'to_member')},
            },
        ),
    ]
