# Generated by Django 5.2 on 2026-01-15 07:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_memberfollow_memberlike'),
        ('tenants', '0002_alter_tenantquota_current_storage_used_mb'),
        ('users', '0004_remove_member_max_trial_licenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberfollow',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='memberlike',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否删除'),
        ),
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='点赞时间')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户代理')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='cms.article', verbose_name='被点赞文章')),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_likes', to='users.member', verbose_name='点赞发起者')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_likes', to='tenants.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '文章点赞',
                'verbose_name_plural': '文章点赞',
                'db_table': 'interactions_article_like',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['from_member', 'created_at'], name='interaction_from_me_9d23fd_idx'), models.Index(fields=['article', 'created_at'], name='interaction_article_3c81d2_idx'), models.Index(fields=['tenant', 'from_member'], name='interaction_tenant__d4bd41_idx'), models.Index(fields=['tenant', 'article'], name='interaction_tenant__908ae6_idx')],
                'unique_together': {('from_member', 'article')},
            },
        ),
    ]
