# Generated by Django 5.2 on 2025-10-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Email for replies (required for anonymous users)', max_length=254, null=True, verbose_name='Contact Email'),
        ),
    ]
