# Generated by Django 5.2 on 2025-11-21 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('feedbacks', '0002_alter_feedback_contact_email'),
        ('tenants', '0002_alter_tenantquota_current_storage_used_mb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='software',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='software',
            name='category',
        ),
        migrations.RemoveField(
            model_name='software',
            name='tenant',
        ),
        migrations.AlterUniqueTogether(
            name='softwarecategory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='softwarecategory',
            name='tenant',
        ),
        migrations.AlterUniqueTogether(
            name='softwareversion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='softwareversion',
            name='software',
        ),
        migrations.RemoveField(
            model_name='softwareversion',
            name='tenant',
        ),
        migrations.RemoveIndex(
            model_name='feedback',
            name='feedback_fe_softwar_c6e970_idx',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='software',
        ),
        migrations.AddField(
            model_name='feedback',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='applications.application', verbose_name='Related Application'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='application_version',
            field=models.ForeignKey(blank=True, help_text='Related to specific application version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='applications.applicationversion', verbose_name='Application Version'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['application', 'status'], name='feedback_fe_applica_9983cd_idx'),
        ),
        migrations.DeleteModel(
            name='Software',
        ),
        migrations.DeleteModel(
            name='SoftwareCategory',
        ),
        migrations.DeleteModel(
            name='SoftwareVersion',
        ),
    ]
