# Generated by Django 5.2 on 2025-11-21 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_alter_software_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='application_version',
        ),
    ]
