# Generated by Django 5.2 on 2025-11-26 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_application_logo'),
        ('feedbacks', '0004_remove_feedback_application_version'),
        ('tenants', '0002_alter_tenantquota_current_storage_used_mb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('reply', 'Reply Notification'), ('status_change', 'Status Change'), ('verification', 'Email Verification'), ('welcome', 'Welcome Email'), ('new_feedback', 'New Feedback Notification')], max_length=20, verbose_name='Template Type'),
        ),
        migrations.AlterField(
            model_name='feedbackemaillog',
            name='email_type',
            field=models.CharField(choices=[('reply', 'Reply Notification'), ('status_change', 'Status Change'), ('verification', 'Email Verification'), ('summary', 'Summary Report'), ('new_feedback', 'New Feedback Notification')], max_length=20, verbose_name='Email Type'),
        ),
        migrations.CreateModel(
            name='FeedbackNotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('is_enabled', models.BooleanField(default=True, help_text='是否启用新反馈邮件通知', verbose_name='启用通知')),
                ('application', models.OneToOneField(help_text='每个应用只能有一个通知配置', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_notification_config', to='applications.application', verbose_name='关联应用')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '反馈通知配置',
                'verbose_name_plural': '反馈通知配置',
                'db_table': 'feedback_notification_config',
            },
        ),
        migrations.CreateModel(
            name='FeedbackNotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('email', models.EmailField(help_text='接收通知的邮箱地址', max_length=254, verbose_name='邮箱地址')),
                ('name', models.CharField(blank=True, help_text='可选，用于邮件称呼', max_length=100, null=True, verbose_name='接收者姓名')),
                ('is_active', models.BooleanField(default=True, help_text='是否接收通知', verbose_name='启用')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='feedbacks.feedbacknotificationconfig', verbose_name='通知配置')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '通知接收者',
                'verbose_name_plural': '通知接收者',
                'db_table': 'feedback_notification_recipient',
                'ordering': ['name', 'email'],
            },
        ),
        migrations.AddIndex(
            model_name='feedbacknotificationconfig',
            index=models.Index(fields=['tenant', 'application'], name='feedback_no_tenant__fbf989_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacknotificationconfig',
            index=models.Index(fields=['is_enabled'], name='feedback_no_is_enab_d22c1e_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacknotificationrecipient',
            index=models.Index(fields=['config', 'is_active'], name='feedback_no_config__432a01_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacknotificationrecipient',
            index=models.Index(fields=['email'], name='feedback_no_email_408043_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feedbacknotificationrecipient',
            unique_together={('config', 'email')},
        ),
    ]
