# Generated by Django 5.2 on 2025-07-16 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='配置名称')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.JSONField(default=dict, verbose_name='配置值')),
                ('type', models.CharField(choices=[('menu', '菜单配置'), ('system', '系统配置'), ('feature', '功能配置'), ('other', '其他配置')], default='other', max_length=20, verbose_name='配置类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='配置描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_configs', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_configs', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'db_table': 'common_config',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50, verbose_name='IP地址')),
                ('request_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('OPTIONS', 'OPTIONS'), ('HEAD', 'HEAD')], max_length=10, verbose_name='请求方法')),
                ('request_path', models.CharField(max_length=255, verbose_name='请求路径')),
                ('view_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='视图名称')),
                ('query_params', models.JSONField(blank=True, null=True, verbose_name='查询参数')),
                ('request_body', models.JSONField(blank=True, null=True, verbose_name='请求体')),
                ('status_code', models.IntegerField(verbose_name='状态码')),
                ('response_time', models.IntegerField(verbose_name='响应时间(ms)')),
                ('status_type', models.CharField(choices=[('success', '成功'), ('error', '错误')], max_length=10, verbose_name='状态类型')),
                ('response_body', models.JSONField(blank=True, null=True, verbose_name='响应体')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to='tenants.tenant', verbose_name='租户')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'API日志',
                'verbose_name_plural': 'API日志',
                'db_table': 'common_api_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='common_api__user_id_a47d29_idx'), models.Index(fields=['tenant'], name='common_api__tenant__71d648_idx'), models.Index(fields=['request_path'], name='common_api__request_1cd2e5_idx'), models.Index(fields=['status_code'], name='common_api__status__d116cf_idx'), models.Index(fields=['created_at'], name='common_api__created_7210d5_idx')],
            },
        ),
    ]
