# Generated by Django 5.2 on 2025-04-21 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50, verbose_name='IP地址')),
                ('request_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('OPTIONS', 'OPTIONS'), ('HEAD', 'HEAD')], max_length=10, verbose_name='请求方法')),
                ('request_path', models.CharField(max_length=255, verbose_name='请求路径')),
                ('query_params', models.JSONField(blank=True, null=True, verbose_name='查询参数')),
                ('request_body', models.JSONField(blank=True, null=True, verbose_name='请求体')),
                ('status_code', models.IntegerField(verbose_name='状态码')),
                ('response_time', models.IntegerField(verbose_name='响应时间(ms)')),
                ('status_type', models.CharField(choices=[('success', '成功'), ('error', '错误')], max_length=10, verbose_name='状态类型')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': 'API日志',
                'verbose_name_plural': 'API日志',
                'db_table': 'common_api_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
