# Generated by Django 5.2 on 2025-04-21 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apilog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['user'], name='common_api__user_id_a47d29_idx'),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['tenant'], name='common_api__tenant__71d648_idx'),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['request_path'], name='common_api__request_1cd2e5_idx'),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['status_code'], name='common_api__status__d116cf_idx'),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['created_at'], name='common_api__created_7210d5_idx'),
        ),
    ]
