# Generated by Django 5.2 on 2026-03-23 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('tenants', '0002_alter_tenantquota_current_storage_used_mb'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilog',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='apilog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='租户'),
        ),
    ]
