# Generated by Django 5.2 on 2025-04-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilog',
            name='response_body',
            field=models.JSONField(blank=True, null=True, verbose_name='响应体'),
        ),
        migrations.AddField(
            model_name='apilog',
            name='view_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='视图名称'),
        ),
    ]
