# Generated by Django 5.2 on 2025-10-25 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_accesslog_ip_address'),
        ('tenants', '0002_alter_tenantquota_current_storage_used_mb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='上级文章，用于创建文章层级结构（如系列文章、章节等）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.article', verbose_name='父文章'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['parent'], name='cms_article_parent__66bf81_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['tenant', 'parent'], name='cms_article_tenant__c7a433_idx'),
        ),
    ]
