# Generated by Django 5.2 on 2025-10-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_add_article_parent_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_image_small',
            field=models.CharField(blank=True, help_text='封面图片的缩略图版本', max_length=255, null=True, verbose_name='封面小图'),
        ),
    ]
