# Generated by Django 5.2 on 2025-10-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_add_article_cover_image_small'),
        ('tenants', '0002_alter_tenantquota_current_storage_used_mb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-is_pinned', 'sort_order', 'name'], 'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AddField(
            model_name='category',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='是否置顶'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_pinned'], name='cms_categor_is_pinn_66ade4_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tenant', 'is_pinned'], name='cms_categor_tenant__7a1928_idx'),
        ),
    ]
