# Generated by Django 5.2 on 2025-11-09 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_add_category_translation'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('tenants', '0002_alter_tenantquota_current_storage_used_mb'),
        ('users', '0004_remove_member_max_trial_licenses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 步骤1: 添加新字段（保留旧字段）
        migrations.RunSQL(
            sql="""
                ALTER TABLE cms_article 
                ADD COLUMN author_content_type_id INT NULL,
                ADD COLUMN author_object_id INT UNSIGNED NULL,
                ADD CONSTRAINT cms_article_author_content_type_fk 
                    FOREIGN KEY (author_content_type_id) 
                    REFERENCES django_content_type(id);
            """,
            reverse_sql="""
                ALTER TABLE cms_article 
                DROP FOREIGN KEY cms_article_author_content_type_fk,
                DROP COLUMN author_content_type_id,
                DROP COLUMN author_object_id;
            """,
        ),
        
        # 步骤2: 迁移数据
        migrations.RunSQL(
            sql="""
                UPDATE cms_article 
                SET author_content_type_id = (
                    SELECT id FROM django_content_type 
                    WHERE app_label='users' AND model='user' LIMIT 1
                ),
                author_object_id = author_id
                WHERE author_id IS NOT NULL;
            """,
            reverse_sql="""
                UPDATE cms_article 
                SET author_id = author_object_id
                WHERE author_content_type_id = (
                    SELECT id FROM django_content_type 
                    WHERE app_label='users' AND model='user' LIMIT 1
                ) AND author_object_id IS NOT NULL;
            """,
        ),
        
        # 步骤3: 删除旧字段
        migrations.RunSQL(
            sql="""
                ALTER TABLE cms_article 
                DROP FOREIGN KEY cms_article_author_id_64970b07_fk_users_user_id,
                DROP COLUMN author_id;
            """,
            reverse_sql="""
                ALTER TABLE cms_article 
                ADD COLUMN author_id BIGINT NULL,
                ADD CONSTRAINT cms_article_author_id_64970b07_fk_users_user_id 
                    FOREIGN KEY (author_id) 
                    REFERENCES users_user(id);
            """,
        ),
        
        # 步骤4: 添加索引
        migrations.RunSQL(
            sql="""
                CREATE INDEX cms_article_author__935039_idx 
                ON cms_article(author_content_type_id, author_object_id);
                
                CREATE INDEX cms_article_tenant__cc6d2a_idx 
                ON cms_article(tenant_id, author_content_type_id, author_object_id);
            """,
            reverse_sql="""
                DROP INDEX cms_article_author__935039_idx ON cms_article;
                DROP INDEX cms_article_tenant__cc6d2a_idx ON cms_article;
            """,
        ),
        
        # 步骤5: 同步Django状态（告诉Django模型已更改）
        migrations.AlterField(
            model_name='article',
            name='author_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_articles_as_author', to='contenttypes.contenttype', verbose_name='作者类型'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author_object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='作者ID'),
        ),
    ]
