# Generated by Django 5.2 on 2025-11-13 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_replace_generic_fk_with_dual_fk'),
        ('tenants', '0002_alter_tenantquota_current_storage_used_mb'),
        ('users', '0004_remove_member_max_trial_licenses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='article',
            name='article_one_author_required',
        ),
        migrations.RenameIndex(
            model_name='article',
            new_name='cms_article_user_id_bacb9b_idx',
            old_name='cms_article_user_idx',
        ),
        migrations.RenameIndex(
            model_name='article',
            new_name='cms_article_member__11bd62_idx',
            old_name='cms_article_member_idx',
        ),
        migrations.RenameIndex(
            model_name='article',
            new_name='cms_article_tenant__3e9ef5_idx',
            old_name='cms_article_tenant_user_idx',
        ),
        migrations.RenameIndex(
            model_name='article',
            new_name='cms_article_tenant__01419f_idx',
            old_name='cms_article_tenant_member_idx',
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AddField(
            model_name='comment',
            name='member',
            field=models.ForeignKey(blank=True, help_text='如果评论者是Member，此字段非空', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_comments', to='users.member', verbose_name='Member用户'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='member',
            field=models.ForeignKey(blank=True, help_text='如果操作者是Member，此字段非空', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='users.member', verbose_name='Member用户'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_type',
            field=models.CharField(choices=[('markdown', 'Markdown'), ('html', 'HTML'), ('image', 'Image'), ('image_upload', 'Image Upload'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File'), ('link', 'Link'), ('quote', 'Quote'), ('code', 'Code'), ('table', 'Table'), ('list', 'List')], default='markdown', max_length=20, verbose_name='内容类型'),
        ),
        migrations.AlterField(
            model_name='article',
            name='member',
            field=models.ForeignKey(blank=True, help_text='如果作者是Member，此字段非空', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='users.member', verbose_name='Member作者'),
        ),
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(blank=True, help_text='如果作者是管理员User，此字段非空', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='管理员作者'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, help_text='如果评论者是管理员User，此字段非空', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_comments', to=settings.AUTH_USER_MODEL, verbose_name='管理员用户'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='如果操作者是管理员User，此字段非空', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='管理员用户'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['member'], name='cms_comment_member__139f28_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['tenant', 'user'], name='cms_comment_tenant__1c0639_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['tenant', 'member'], name='cms_comment_tenant__39f0ee_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['member'], name='cms_operati_member__fc506b_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['tenant', 'user'], name='cms_operati_tenant__1f3512_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['tenant', 'member'], name='cms_operati_tenant__ee93cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('member__isnull', True), ('user__isnull', False)), models.Q(('member__isnull', False), ('user__isnull', True)), _connector='OR'), name='article_one_author_required'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('guest_name__isnull', True), ('member__isnull', True), ('user__isnull', False)), models.Q(('guest_name__isnull', True), ('member__isnull', False), ('user__isnull', True)), models.Q(('guest_name__isnull', False), ('member__isnull', True), ('user__isnull', True)), _connector='OR'), name='comment_one_author_type_required'),
        ),
        migrations.AddConstraint(
            model_name='operationlog',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('member__isnull', True), ('user__isnull', False)), models.Q(('member__isnull', False), ('user__isnull', True)), _connector='OR'), name='operation_log_one_operator_required'),
        ),
    ]
