# Generated by Django 5.2 on 2025-11-21 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('cms', '0009_remove_article_article_one_author_required_and_more'),
        ('tenants', '0002_alter_tenantquota_current_storage_used_mb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(default=0, help_text='在该应用中的显示顺序，数字越小越靠前', verbose_name='显示顺序')),
                ('is_featured', models.BooleanField(default=False, help_text='是否在该应用中作为特色文章展示', verbose_name='特色展示')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='关联时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文章-应用关联',
                'verbose_name_plural': '文章-应用关联',
                'db_table': 'cms_article_application',
                'ordering': ['display_order', '-assigned_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='interaction',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='article',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='user',
        ),
        migrations.AddField(
            model_name='category',
            name='application',
            field=models.ForeignKey(blank=True, help_text='分类所属的应用，留空表示全局分类', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='applications.application', verbose_name='关联应用'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['application'], name='cms_categor_applica_57bcec_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tenant', 'application'], name='cms_categor_tenant__55d50e_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tenant', 'application', 'is_active'], name='cms_categor_tenant__656adc_idx'),
        ),
        migrations.AddField(
            model_name='articleapplication',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application', verbose_name='关联应用'),
        ),
        migrations.AddField(
            model_name='articleapplication',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.article', verbose_name='关联文章'),
        ),
        migrations.AddField(
            model_name='articleapplication',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_applications', to='tenants.tenant', verbose_name='所属租户'),
        ),
        migrations.DeleteModel(
            name='Interaction',
        ),
        migrations.AddIndex(
            model_name='articleapplication',
            index=models.Index(fields=['application', 'article'], name='cms_article_applica_31438f_idx'),
        ),
        migrations.AddIndex(
            model_name='articleapplication',
            index=models.Index(fields=['article', 'application'], name='cms_article_article_8374bf_idx'),
        ),
        migrations.AddIndex(
            model_name='articleapplication',
            index=models.Index(fields=['tenant', 'application'], name='cms_article_tenant__7e4b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='articleapplication',
            index=models.Index(fields=['application', 'display_order'], name='cms_article_applica_45e79f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='articleapplication',
            unique_together={('article', 'application')},
        ),
    ]
