# Generated by Django 5.2 on 2025-04-21 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='租户名称')),
                ('status', models.CharField(choices=[('active', '活跃'), ('suspended', '暂停'), ('deleted', '已删除')], default='active', max_length=20, verbose_name='状态')),
                ('contact_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系人姓名')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='联系人邮箱')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系人电话')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '租户',
                'verbose_name_plural': '租户',
                'db_table': 'tenant',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_users', models.IntegerField(default=10, verbose_name='最大用户数')),
                ('max_admins', models.IntegerField(default=2, verbose_name='最大管理员数')),
                ('max_storage_mb', models.IntegerField(default=1024, verbose_name='最大存储空间(MB)')),
                ('max_products', models.IntegerField(default=100, verbose_name='最大产品数')),
                ('current_storage_used_mb', models.IntegerField(default=0, verbose_name='当前已用存储空间(MB)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '租户配额',
                'verbose_name_plural': '租户配额',
                'db_table': 'tenant_quota',
            },
        ),
    ]
