# Generated by Django 5.2 on 2025-04-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='code',
            field=models.CharField(blank=True, help_text='用于API和集成的唯一标识符', max_length=50, null=True, unique=True, verbose_name='租户代码'),
        ),
    ]
