# Generated by Django 5.2 on 2025-10-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantquota',
            name='current_storage_used_mb',
            field=models.IntegerField(default=0, verbose_name='current已用存储空间(MB)'),
        ),
    ]
