# Generated by Django 5.2 on 2025-06-05 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantBusinessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='公司名称')),
                ('legal_representative', models.CharField(max_length=50, verbose_name='法定代表人')),
                ('unified_social_credit_code', models.CharField(max_length=50, unique=True, verbose_name='统一社会信用代码')),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='注册号')),
                ('company_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='公司类型')),
                ('registered_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='注册资本')),
                ('registered_capital_currency', models.CharField(blank=True, default='CNY', max_length=20, null=True, verbose_name='注册资本币种')),
                ('business_scope', models.TextField(blank=True, null=True, verbose_name='经营范围')),
                ('establishment_date', models.DateField(blank=True, null=True, verbose_name='成立日期')),
                ('business_term_start', models.DateField(blank=True, null=True, verbose_name='营业期限开始日期')),
                ('business_term_end', models.DateField(blank=True, null=True, verbose_name='营业期限结束日期')),
                ('registration_authority', models.CharField(blank=True, max_length=100, null=True, verbose_name='登记机关')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='核准日期')),
                ('business_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='企业状态')),
                ('registered_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='注册地址')),
                ('office_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='办公地址')),
                ('contact_person', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='电子邮箱')),
                ('website', models.URLField(blank=True, null=True, verbose_name='公司网站')),
                ('license_image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='营业执照图片URL')),
                ('license_image_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='营业执照图片存储路径')),
                ('license_issue_date', models.DateField(blank=True, null=True, verbose_name='营业执照发证日期')),
                ('license_expiry_date', models.DateField(blank=True, null=True, verbose_name='营业执照到期日期')),
                ('verification_status', models.CharField(choices=[('pending', '待验证'), ('verified', '已验证'), ('rejected', '已拒绝'), ('expired', '已过期')], default='pending', max_length=20, verbose_name='验证状态')),
                ('verification_time', models.DateTimeField(blank=True, null=True, verbose_name='验证时间')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='拒绝原因')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_business_infos', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_info', to='tenants.tenant', verbose_name='租户')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_business_infos', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('verification_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_businesses', to=settings.AUTH_USER_MODEL, verbose_name='验证人')),
            ],
            options={
                'verbose_name': '租户企业信息',
                'verbose_name_plural': '租户企业信息',
                'db_table': 'tenant_business_info',
            },
        ),
    ]
