# Generated by Django 5.2 on 2025-07-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenantbusinessinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TenantBusinessInfo',
        ),
    ]
