# Generated by Django 5.2 on 2026-03-23 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('we_rss', '0002_align_with_base_model'),
        ('we_rss', '0002_wechatarticle_type'),
    ]

    operations = [
    ]
