# Generated by Django 5.2 on 2026-03-25 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenantquota_current_storage_used_mb'),
        ('users', '0004_remove_member_max_trial_licenses'),
        ('we_rss', '0003_merge_align_and_article_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wechatarticle',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='wechatarticle',
            name='is_read',
        ),
        migrations.CreateModel(
            name='MemberArticleFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_favorites', to='we_rss.wechatarticle')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='we_rss_article_favorites', to='users.member')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='we_rss_member_article_favorites', to='tenants.tenant')),
            ],
            options={
                'db_table': 'we_rss_member_article_favorite',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'member'], name='we_rss_memb_tenant__0b4f98_idx'), models.Index(fields=['tenant', 'article'], name='we_rss_memb_tenant__05c285_idx')],
                'constraints': [models.UniqueConstraint(fields=('member', 'article'), name='we_rss_member_article_favorite_unique')],
            },
        ),
        migrations.CreateModel(
            name='MemberFeedSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_subscriptions', to='we_rss.wechatfeed')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='we_rss_feed_subscriptions', to='users.member')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='we_rss_member_feed_subscriptions', to='tenants.tenant')),
            ],
            options={
                'db_table': 'we_rss_member_feed_subscription',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'member'], name='we_rss_memb_tenant__560510_idx'), models.Index(fields=['tenant', 'feed'], name='we_rss_memb_tenant__3d7775_idx')],
                'constraints': [models.UniqueConstraint(fields=('member', 'feed'), name='we_rss_member_feed_subscription_unique')],
            },
        ),
    ]
