# Generated by Django 5.2 on 2026-03-26 05:02

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenantquota_current_storage_used_mb'),
        ('users', '0004_remove_member_max_trial_licenses'),
        ('we_rss', '0004_remove_wechatarticle_is_favorite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, default='', max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('is_pinned', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='we_rss_member_tags', to='users.member')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'db_table': 'we_rss_member_tag',
                'ordering': ['-is_pinned', 'sort_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MemberFeedTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_tag_relations', to='we_rss.wechatfeed')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='we_rss_feed_tag_relations', to='users.member')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='we_rss_member_feed_tag_relations', to='tenants.tenant')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_relations', to='we_rss.membertag')),
            ],
            options={
                'db_table': 'we_rss_member_feed_tag_relation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberArticleTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_tag_relations', to='we_rss.wechatarticle')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='we_rss_article_tag_relations', to='users.member')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='we_rss_member_article_tag_relations', to='tenants.tenant')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_relations', to='we_rss.membertag')),
            ],
            options={
                'db_table': 'we_rss_member_article_tag_relation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='membertag',
            index=models.Index(fields=['tenant', 'member'], name='we_rss_memb_tenant__7e4dc4_idx'),
        ),
        migrations.AddConstraint(
            model_name='membertag',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('member'), name='we_rss_member_tag_member_lower_name_unique'),
        ),
        migrations.AddIndex(
            model_name='memberfeedtagrelation',
            index=models.Index(fields=['tenant', 'member'], name='we_rss_memb_tenant__55b039_idx'),
        ),
        migrations.AddIndex(
            model_name='memberfeedtagrelation',
            index=models.Index(fields=['tenant', 'feed'], name='we_rss_memb_tenant__260265_idx'),
        ),
        migrations.AddIndex(
            model_name='memberfeedtagrelation',
            index=models.Index(fields=['tenant', 'tag'], name='we_rss_memb_tenant__00cba2_idx'),
        ),
        migrations.AddConstraint(
            model_name='memberfeedtagrelation',
            constraint=models.UniqueConstraint(fields=('member', 'tag', 'feed'), name='we_rss_member_feed_tag_relation_unique'),
        ),
        migrations.AddIndex(
            model_name='memberarticletagrelation',
            index=models.Index(fields=['tenant', 'member'], name='we_rss_memb_tenant__11484b_idx'),
        ),
        migrations.AddIndex(
            model_name='memberarticletagrelation',
            index=models.Index(fields=['tenant', 'article'], name='we_rss_memb_tenant__2bc331_idx'),
        ),
        migrations.AddIndex(
            model_name='memberarticletagrelation',
            index=models.Index(fields=['tenant', 'tag'], name='we_rss_memb_tenant__3d3040_idx'),
        ),
        migrations.AddConstraint(
            model_name='memberarticletagrelation',
            constraint=models.UniqueConstraint(fields=('member', 'tag', 'article'), name='we_rss_member_article_tag_relation_unique'),
        ),
    ]
