# Generated by Django 5.2 on 2026-04-05 12:45

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_alter_tenantquota_current_storage_used_mb"),
        ("users", "0004_remove_member_max_trial_licenses"),
        ("we_rss", "0007_expand_feed_sync_task_types_and_statuses"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberSeoKeyword",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name="更新时间")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否删除")),
                ("keyword", models.CharField(max_length=255)),
                ("search_index", models.PositiveIntegerField(default=0)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="we_rss_seo_keywords",
                        to="users.member",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                        verbose_name="租户",
                    ),
                ),
            ],
            options={
                "db_table": "we_rss_member_seo_keyword",
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MemberTagSeoKeywordRelation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="we_rss_tag_seo_keyword_relations",
                        to="users.member",
                    ),
                ),
                (
                    "seo_keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keyword_tag_relations",
                        to="we_rss.memberseokeyword",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seo_keyword_relations",
                        to="we_rss.membertag",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="we_rss_member_tag_seo_keyword_relations",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "we_rss_member_tag_seo_keyword_relation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="memberseokeyword",
            index=models.Index(fields=["tenant", "member"], name="we_rss_memb_tenant__a1adcc_idx"),
        ),
        migrations.AddIndex(
            model_name="memberseokeyword",
            index=models.Index(fields=["tenant", "member", "search_index"], name="we_rss_memb_tenant__40fb9f_idx"),
        ),
        migrations.AddIndex(
            model_name="memberseokeyword",
            index=models.Index(fields=["tenant", "member", "keyword"], name="we_rss_memb_tenant__1bedf6_idx"),
        ),
        migrations.AddConstraint(
            model_name="memberseokeyword",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("keyword"),
                models.F("member"),
                name="we_rss_member_seo_keyword_member_lower_keyword_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="membertagseokeywordrelation",
            index=models.Index(fields=["tenant", "member"], name="we_rss_memb_tenant__bf5f23_idx"),
        ),
        migrations.AddIndex(
            model_name="membertagseokeywordrelation",
            index=models.Index(fields=["tenant", "tag"], name="we_rss_memb_tenant__7ca45b_idx"),
        ),
        migrations.AddIndex(
            model_name="membertagseokeywordrelation",
            index=models.Index(fields=["tenant", "seo_keyword"], name="we_rss_memb_tenant__c97fb7_idx"),
        ),
        migrations.AddConstraint(
            model_name="membertagseokeywordrelation",
            constraint=models.UniqueConstraint(
                fields=("member", "tag", "seo_keyword"),
                name="we_rss_member_tag_seo_keyword_relation_unique",
            ),
        ),
    ]
