"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import datetime
import pymysql
import logging.handlers  # 导入logging.handlers模块

# 使用pymysql代替mysqlclient
pymysql.install_as_MySQLdb()

# 加载.env文件
load_dotenv()


def get_required_env(key, default=None):
    """获取必需的环境变量"""
    value = os.getenv(key, default)
    if value is None:
        raise ValueError(f"Required environment variable {key} is not set")
    return value


def get_env_with_validation(key, validator, default=None):
    """获取并验证环境变量"""
    value = os.getenv(key, default)
    if value is not None:
        try:
            return validator(value)
        except Exception as e:
            raise ValueError(f"Invalid value for environment variable {key}: {e}")
    return value

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_required_env('SECRET_KEY', 'django-insecure-w7&3bzjc1s*bty@)%c3w&#fro!wu5@(9jxac46lqm^klo9^1df')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env_with_validation('INFO', lambda x: x.lower() == 'true', 'True')

# 从环境变量读取日志输出方式，默认跟随DEBUG设置
LOG_TO_CONSOLE = os.getenv('LOG_TO_CONSOLE', str(DEBUG)).lower() == 'true'

# Feature flags
# 是否强制成员/匿名在CMS路径携带并校验 X-Tenant-ID（默认开启，可用环境变量关闭以便灰度）
FEATURE_ENFORCE_TENANT_HEADER_FOR_MEMBER = get_env_with_validation(
    'FEATURE_ENFORCE_TENANT_HEADER_FOR_MEMBER', lambda x: x.lower() == 'true', 'True'
)

# 允许所有主机访问（开发环境）
# 警告：生产环境应指定具体域名，例如 ['yourdomain.com', 'www.yourdomain.com']
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # 第三方应用
    'rest_framework',
    'drf_yasg',
    'corsheaders',
    'drf_spectacular',
    'drf_spectacular_sidecar',  # 提供Swagger UI和ReDoc的静态资源
    'parler',  # 多语言支持
    
    # 自定义应用
    'common',
    'tenants',
    'users',
    'rbac',  # RBAC权限系统
    'docs_view',  # 新添加的文档查看应用
    'check_system',  # 打卡系统应用
    'cms',  # CMS应用
    'menus',  # 菜单管理应用
    'charts',  # 图表应用
    'customers',  # 客户管理应用
    'orders',  # 订单管理应用
    'licenses',  # 许可证管理应用
    'points',  # 多租户积分系统
    'applications',  # 应用管理（整合licenses和feedbacks的软件实体）
    'feedbacks',  # User Feedback System
    'interactions',  # 用户互动应用（收藏、点赞等）
]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',  # 静态文件优化
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS中间件提前
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',  # 保持CSRF中间件位置
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 自定义中间件放在Django核心中间件之后
    'common.middleware.api_auth_middleware.APIAuthMiddleware',
    'common.middleware.tenant_middleware.TenantMiddleware',
    'common.middleware.enhanced_api_logging_middleware.EnhancedAPILoggingMiddleware',
    'common.middleware.browser_console_logging_middleware.BrowserConsoleLoggingMiddleware',
    'common.middleware.response_standardization_middleware.ResponseStandardizationMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'multi_tenant_db_dev'),
        'USER': os.getenv('DB_USER', 'root'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'password'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'use_unicode': True,
            'init_command': "SET NAMES 'utf8mb4' COLLATE 'utf8mb4_unicode_ci'",
            'autocommit': True,
        },
        'CONN_MAX_AGE': 600,  # 10分钟连接池
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# 为开发环境添加静态文件目录
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 自定义用户模型
AUTH_USER_MODEL = 'users.User'

# 租户验证设置
# 只有URL路径中包含这些关键字的请求才会被租户中间件处理
TENANT_REQUIRED_PATHS = [
    '/cms/',  # CMS相关API
    '/customers/',  # cuAPI
    '/orders/',  # 订单相关API 
    
    # 可以添加其他需要租户验证的关键字...
]

# REST Framework 设置
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'common.authentication.api_auth.APIJWTAuthentication',
        'common.authentication.web_auth.WebSessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'common.pagination.StandardResultsSetPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'common.exceptions.custom_exception_handler',
    'DEFAULT_RENDERER_CLASSES': (
        'common.renderers.StandardJSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
}

# JWT 设置
JWT_AUTH = {
    'JWT_SECRET_KEY': SECRET_KEY,
    'JWT_ALGORITHM': 'HS256',
    'JWT_EXPIRATION_DELTA': 7 * 24 * 3600,  # 24小时有效期
    'JWT_REFRESH_EXPIRATION_DELTA': 28 * 24 * 3600,  # 7天刷新期
}

# ============================================
# CORS 跨域配置
# ============================================
# 开发环境允许所有来源，生产环境建议使用白名单
CORS_ALLOW_ALL_ORIGINS = True  # 允许所有来源（适用于开发和API服务）

# 如果需要白名单模式，设置 CORS_ALLOW_ALL_ORIGINS = False 并配置以下列表
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://localhost:8848",
    "http://43.142.76.105",
    "http://43.142.76.105:8000",
    "http://43.142.76.105:3000",
    "http://espressox.online",
    "https://espressox.online",
    "http://backend.espressox.online",
    "https://backend.espressox.online",
    "http://admin.espressox.online",
    "https://admin.espressox.online",

    "http://compressx.online",
    "https://compressx.online",
    "http://backend.compressx.online",
    "https://backend.compressx.online",
    "http://admin.compressx.online",
    "https://admin.compressx.online",
    "http://stg.compressx.online",
    "https://stg.compressx.online",
]

CORS_ALLOW_CREDENTIALS = True  # 允许携带凭证（如 cookies）

# 允许的 HTTP 方法
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# 允许的 HTTP 请求头
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",  # 明确允许CSRF token头
    "x-requested-with",
    "x-tenant-id",
]

# 允许前端访问的响应头
CORS_EXPOSE_HEADERS = [
    "content-type",
    "x-csrftoken",
]

# CSRF 安全配置
CSRF_COOKIE_AGE = 31449600  # 1年
CSRF_COOKIE_DOMAIN = None
CSRF_COOKIE_HTTPONLY = False  # 允许JavaScript访问CSRF cookie
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_COOKIE_PATH = '/'
CSRF_COOKIE_SAMESITE = 'Lax'  # 重要：设置为Lax而不是Strict
CSRF_COOKIE_SECURE = False if DEBUG else True  # 开发环境设为False
CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'

# CSRF 受信任的源（重要：解决跨域CSRF问题）
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://43.142.76.105',
    'http://43.142.76.105:8000',
    'http://43.142.76.105:3000',
    'http://espressox.online',
    'https://espressox.online',
    'http://backend.espressox.online',
    'https://backend.espressox.online',
    'http://admin.espressox.online',
    'https://admin.espressox.online',

    "http://compressx.online",
    "https://compressx.online",
    "http://backend.compressx.online",
    "https://backend.compressx.online",
    "http://admin.compressx.online",
    "https://admin.compressx.online",
    "http://stg.compressx.online",
    "https://stg.compressx.online",
]

CSRF_USE_SESSIONS = False

# Spectacular API 文档设置
SPECTACULAR_SETTINGS = {
    'TITLE': '多租户用户管理系统 API',
    'DESCRIPTION': '用于管理多租户用户系统的REST API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
    },
    'SWAGGER_UI_DIST': 'SIDECAR',  # 使用内置的Swagger UI发行版
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',  # 使用内置的Redoc发行版
    # 调试选项
    'DISABLE_ERRORS_AND_WARNINGS': False,
    # 忽略某些特定警告
    'DISABLE_WARNINGS': {
        'enum_collision': True,
    },
    # 添加认证设置
    'SECURITY': [{'Bearer': []}],
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': '请输入 "Bearer {token}" 格式的JWT令牌'
        }
    },
    # 只使用APIJWTAuthentication，避免重复的Bearer组件
    'AUTHENTICATION_WHITELIST': [
        'common.authentication.api_auth.APIJWTAuthentication',
    ],
    # 添加JWT认证映射
    'COMPONENT_SPLIT_REQUEST': True,
    'COMPONENT_NO_READ_ONLY_REQUIRED': False,
    
    # 设置API路径预处理器，对所有路径应用安全要求
    'PREPROCESSING_HOOKS': ['common.schema.spectacular_hooks.add_security_requirement'],
    
    # 设置后处理钩子，用于自定义标签
    'POSTPROCESSING_HOOKS': ['common.schema.spectacular_hooks.customize_feedback_tags'],
    
    # 扩展类
    'EXTENSIONS': [
        'common.schema.spectacular_extensions.JWTAuthenticationScheme',
        'common.schema.spectacular_extensions.APIJWTAuthenticationScheme',
    ],
    # 排除session和basic认证
    'AUTHENTICATION_WHITELIST': [
        'common.authentication.jwt_auth.JWTAuthentication',
        'common.authentication.api_auth.APIJWTAuthentication',
    ],
    
    # 解决枚举命名冲突
    'ENUM_NAME_OVERRIDES': {
        # 使用空字典来忽略这个设置，我们将在模型或schema中直接添加装饰器来处理
    },
}

# 是否启用debug日志文件记录
DEBUG_LOG_ENABLED = True

# 确保日志目录存在
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)

# 日志保留天数
LOG_RETENTION_DAYS = 15

# 日志文件名格式
def get_log_filename(base_name):
    """生成带日期的日志文件名"""
    from datetime import datetime
    date_str = datetime.now().strftime('%Y-%m-%d')
    return os.path.join(LOGS_DIR, f"{base_name}.{date_str}.log")

# 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',  # 使用轮转日志
            'filename': get_log_filename('INFO'),  # 使用带日期的文件名
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 5,  # 保留5个备份文件
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',  # 使用轮转日志
            'filename': get_log_filename('error'),  # 使用带日期的文件名
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 5,  # 保留5个备份文件
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'django': {
            # 根据LOG_TO_CONSOLE环境变量决定日志输出方式
            'handlers': ['console'] if LOG_TO_CONSOLE else ['file', 'error_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'drf_spectacular': {
            # 根据LOG_TO_CONSOLE环境变量决定日志输出方式
            'handlers': ['console'] if LOG_TO_CONSOLE else ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'users': {
            'handlers': ['console'] if LOG_TO_CONSOLE else ['file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# 邮件设置（QQ邮箱SMTP）
# 支持通过环境变量控制：EMAIL_USE_CONSOLE=true 使用控制台模式（仅调试）
USE_CONSOLE_EMAIL = os.getenv('EMAIL_USE_CONSOLE', 'false').lower() == 'true'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' if USE_CONSOLE_EMAIL else 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')  # QQ邮箱地址
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')  # QQ邮箱授权码
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER if EMAIL_HOST_USER else 'noreply@example.com')  # 发件人邮箱
EMAIL_TIMEOUT = 30  # SMTP 连接超时（秒）

# 前端URL（用于构建密码重置链接）
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')

# WhiteNoise配置
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
WHITENOISE_USE_FINDERS = True
WHITENENOISE_AUTOREFRESH = DEBUG

# 租户中间件配置（已完成重构，使用新架构）
# 租户中间件调试模式（启用详细日志）
TENANT_MIDDLEWARE_DEBUG = get_env_with_validation(
    'TENANT_MIDDLEWARE_DEBUG', lambda x: x.lower() == 'true', 'True' if DEBUG else 'False'
)

# 租户中间件性能监控（记录处理时间）
TENANT_MIDDLEWARE_PERFORMANCE_MONITORING = get_env_with_validation(
    'TENANT_MIDDLEWARE_PERFORMANCE_MONITORING', lambda x: x.lower() == 'true', 'False'
)

# Celery Configuration
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Celery Task Routes
CELERY_TASK_ROUTES = {
    'feedbacks.tasks.*': {'queue': 'feedbacks'},
}

# Celery Beat Schedule (for periodic tasks)
from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    'cleanup-old-email-logs': {
        'task': 'feedbacks.tasks.cleanup_old_email_logs',
        'schedule': crontab(hour=2, minute=0),  # Run daily at 2 AM
        'args': (90,)  # Keep logs for 90 days
    },
}

# ============================================================================
# Django Parler Configuration (多语言支持)
# ============================================================================

PARLER_LANGUAGES = {
    None: (
        {'code': 'zh-hans', 'name': 'Simplified Chinese'},  # 简体中文
        {'code': 'en', 'name': 'English'},                  # 英文
        {'code': 'zh-hant', 'name': 'Traditional Chinese'}, # 繁体中文
        {'code': 'ja', 'name': 'Japanese'},                 # 日语
        {'code': 'ko', 'name': 'Korean'},                   # 韩语
        {'code': 'fr', 'name': 'French'},                   # 法语
    ),
    'default': {
        'fallbacks': ['zh-hans'],          # 默认回退到简体中文
        'hide_untranslated': False,        # 显示未翻译的内容（使用回退语言）
    }
}

# Parler默认语言
PARLER_DEFAULT_LANGUAGE_CODE = 'zh-hans'

# ============================================================================
# File Upload Settings (文件上传设置)
# ============================================================================
# 增加内存上传大小限制，支持较大文件上传（例如图片、文档等）
# 默认值：2.5MB (2621440 bytes)
# 设置为 10MB，可根据实际需求调整
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB

# 请求体最大大小限制（包括文件上传）
# 设置为 50MB，防止恶意请求
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000  # 表单字段数量限制
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB - 在内存中处理的最大文件大小