# Generated by Django 5.2 on 2025-07-16 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=100, verbose_name='客户名称')),
                ('type', models.CharField(choices=[('enterprise', '公司'), ('individual', '个人'), ('government', '政府机构'), ('nonprofit', '非营利组织'), ('education', '教育机构')], default='company', max_length=20, verbose_name='客户类型')),
                ('value_level', models.CharField(choices=[('platinum', '铂金'), ('gold', '黄金'), ('silver', '白银'), ('bronze', '青铜')], default='normal', max_length=20, verbose_name='价值等级')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '非活跃'), ('potential', '潜在'), ('lost', '流失')], default='active', max_length=20, verbose_name='状态')),
                ('business_license_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='营业执照号')),
                ('tax_identification_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='纳税人识别号')),
                ('registered_capital', models.CharField(blank=True, max_length=50, null=True, verbose_name='注册资本')),
                ('legal_representative', models.CharField(blank=True, max_length=50, null=True, verbose_name='法定代表人')),
                ('registered_address', models.TextField(blank=True, null=True, verbose_name='注册地址')),
                ('business_address', models.TextField(blank=True, null=True, verbose_name='经营地址')),
                ('business_scope', models.TextField(blank=True, null=True, verbose_name='经营范围')),
                ('industry_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='行业类型')),
                ('company_size', models.CharField(blank=True, choices=[('micro', '微型'), ('small', '小型'), ('medium', '中型'), ('large', '大型')], max_length=20, null=True, verbose_name='公司规模')),
                ('establishment_date', models.DateField(blank=True, null=True, verbose_name='成立日期')),
                ('website', models.URLField(blank=True, null=True, verbose_name='公司网站')),
                ('primary_contact_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='主要联系人姓名')),
                ('primary_contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='主要联系人电话')),
                ('primary_contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='主要联系人邮箱')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='开户银行')),
                ('bank_account', models.CharField(blank=True, max_length=100, null=True, verbose_name='银行账号')),
                ('credit_rating', models.CharField(blank=True, max_length=20, null=True, verbose_name='信用等级')),
                ('payment_terms', models.CharField(blank=True, max_length=200, null=True, verbose_name='付款条件')),
                ('special_requirements', models.TextField(blank=True, null=True, verbose_name='特殊要求')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注信息')),
                ('source', models.CharField(blank=True, max_length=50, null=True, verbose_name='客户来源')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='创建者')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='更新者')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'db_table': 'customer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerMemberRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('role', models.CharField(blank=True, help_text='联系人在客户中的角色', max_length=50, null=True, verbose_name='角色')),
                ('is_primary', models.BooleanField(default=False, help_text='是否为该客户的主要联系人', verbose_name='主要联系人')),
                ('remarks', models.TextField(blank=True, help_text='关于该联系人与客户关系的补充说明', null=True, verbose_name='备注')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_relations', to='customers.customer', verbose_name='客户')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_relations', to='users.member', verbose_name='联系人')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '客户-联系人关系',
                'verbose_name_plural': '客户-联系人关系',
                'db_table': 'customer_member_relation',
                'ordering': ['-is_primary', '-created_at'],
                'unique_together': {('customer', 'member')},
            },
        ),
        migrations.CreateModel(
            name='CustomerTenantRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('relation_type', models.CharField(choices=[('provider', '服务提供方'), ('client', '客户方'), ('partner', '合作伙伴'), ('distributor', '分销商'), ('supplier', '供应商'), ('other', '其他')], default='client', help_text='客户与租户之间的关系类型', max_length=20, verbose_name='关系类型')),
                ('is_primary', models.BooleanField(default=False, help_text='是否为该客户的主要租户关系', verbose_name='主要关系')),
                ('contract_number', models.CharField(blank=True, help_text='相关合同编号，如有', max_length=100, null=True, verbose_name='合同编号')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='关系开始日期')),
                ('end_date', models.DateField(blank=True, help_text='留空表示长期有效', null=True, verbose_name='关系结束日期')),
                ('description', models.TextField(blank=True, help_text='详细说明客户与租户之间的关系', null=True, verbose_name='关系描述')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='创建者')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='更新者')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_relations', to='customers.customer', verbose_name='客户')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_relations', to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '客户-租户关系',
                'verbose_name_plural': '客户-租户关系',
                'db_table': 'customer_tenant_relation',
                'ordering': ['-is_primary', '-created_at'],
                'unique_together': {('customer', 'tenant', 'relation_type')},
            },
        ),
    ]
