# Generated by Django 5.2 on 2025-08-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='customermemberrelation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='customermemberrelation',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='customermemberrelation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='customertenantrelation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='customertenantrelation',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='customertenantrelation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间'),
        ),
    ]
