# Generated by Django 5.2 on 2025-07-03 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('tenants', '0003_tenantbusinessinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTenantRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('provider', '服务提供方'), ('client', '客户方'), ('partner', '合作伙伴'), ('distributor', '分销商'), ('supplier', '供应商'), ('other', '其他')], default='client', help_text='客户与租户之间的关系类型', max_length=20, verbose_name='关系类型')),
                ('is_primary', models.BooleanField(default=False, help_text='是否为该客户的主要租户关系', verbose_name='主要关系')),
                ('contract_number', models.CharField(blank=True, help_text='相关合同编号，如有', max_length=100, null=True, verbose_name='合同编号')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='关系开始日期')),
                ('end_date', models.DateField(blank=True, help_text='留空表示长期有效', null=True, verbose_name='关系结束日期')),
                ('description', models.TextField(blank=True, help_text='详细说明客户与租户之间的关系', null=True, verbose_name='关系描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='创建者')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='更新者')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_relations', to='customers.customer', verbose_name='客户')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_relations', to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '客户-租户关系',
                'verbose_name_plural': '客户-租户关系',
                'db_table': 'customer_tenant_relation',
                'ordering': ['-is_primary', '-created_at'],
                'unique_together': {('customer', 'tenant', 'relation_type')},
            },
        ),
    ]
