# Generated by Django 5.2 on 2025-07-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customertenantrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermemberrelation',
            name='remarks',
            field=models.TextField(blank=True, help_text='关于该联系人与客户关系的补充说明', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='type',
            field=models.CharField(choices=[('enterprise', '公司'), ('individual', '个人'), ('government', '政府机构'), ('nonprofit', '非营利组织'), ('education', '教育机构')], default='company', max_length=20, verbose_name='客户类型'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='value_level',
            field=models.CharField(choices=[('platinum', '铂金'), ('gold', '黄金'), ('silver', '白银'), ('bronze', '青铜')], default='normal', max_length=20, verbose_name='价值等级'),
        ),
    ]
