# Generated by Django 5.2 on 2025-07-14 06:41

import django.db.models.deletion
from django.db import migrations, models
import django.db.models.manager


def set_tenant_for_customer_relations(apps, schema_editor):
    """
    为已有的客户和客户关系表设置租户ID
    逻辑：
    1. 如果客户已有租户关系，使用主要租户关系中的租户ID
    2. 如果没有，则使用系统默认租户（ID=1）
    """
    Customer = apps.get_model('customers', 'Customer')
    CustomerTenantRelation = apps.get_model('customers', 'CustomerTenantRelation')
    CustomerMemberRelation = apps.get_model('customers', 'CustomerMemberRelation')
    
    # 默认租户ID（通常是1）
    default_tenant_id = 1
    
    # 为所有客户设置租户
    for customer in Customer.objects.all():
        # 尝试查找主要租户关系
        tenant_relation = CustomerTenantRelation.objects.filter(
            customer=customer, 
            is_primary=True
        ).first()
        
        # 如果没有主要关系，查找任何租户关系
        if not tenant_relation:
            tenant_relation = CustomerTenantRelation.objects.filter(
                customer=customer
            ).first()
        
        # 设置租户ID
        if tenant_relation:
            customer.tenant_id = tenant_relation.tenant_id
        else:
            customer.tenant_id = default_tenant_id
            
        customer.save(update_fields=['tenant_id'])
    
    # 为所有客户-联系人关系设置租户
    for relation in CustomerMemberRelation.objects.all():
        if relation.customer.tenant_id:
            relation.tenant_id = relation.customer.tenant_id
        else:
            relation.tenant_id = default_tenant_id
        
        relation.save(update_fields=['tenant_id'])
    
    # 为所有客户-租户关系设置tenant字段（与租户自身相同）
    for relation in CustomerTenantRelation.objects.all():
        relation.tenant_id = relation.tenant_id  # 设置为关系中的租户ID
        relation.save(update_fields=['tenant_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_code'),
        ('customers', '0003_customermemberrelation_remarks_alter_customer_type_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='customermemberrelation',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='customertenantrelation',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('original_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(db_index=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_set', to='tenants.tenant', verbose_name='租户'),
        ),
        migrations.AddField(
            model_name='customermemberrelation',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='customermemberrelation',
            name='tenant',
            field=models.ForeignKey(db_index=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customermemberrelation_set', to='tenants.tenant', verbose_name='租户'),
        ),
        migrations.AddField(
            model_name='customertenantrelation',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='customermemberrelation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='customermemberrelation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='customertenantrelation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='customertenantrelation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        
        # 添加数据迁移
        migrations.RunPython(
            set_tenant_for_customer_relations,
            migrations.RunPython.noop
        ),
    ]
