-- SQL script to add articles to CMS categories
-- Each leaf category will have 9 articles
-- All articles belong to tenant_id = 1
-- Author ID is assumed to be 1 (adjust if needed)

-- Common cover image URL for all articles
SET @cover_image = 'http://gips3.baidu.com/it/u=3886271102,3123389489&fm=3028&app=3028&f=JPEG&fmt=auto?w=1280&h=960';

-- Current timestamp for creation and update times
SET @now = NOW();

-- First, get the category IDs for reference
-- Note: In a real database, you would use the actual IDs instead of selecting them like this

-- Get parent category ID (Product)
SELECT @product_category_id := id FROM cms_category WHERE name = 'Product' AND tenant_id = 1 LIMIT 1;

-- Get leaf category IDs
SELECT @imagediff_category_id := id FROM cms_category WHERE name = 'ImageDiff' AND tenant_id = 1 LIMIT 1;
SELECT @freetools_category_id := id FROM cms_category WHERE name = 'Free tools' AND tenant_id = 1 LIMIT 1;
SELECT @affiliate_category_id := id FROM cms_category WHERE name = 'Affiliate' AND tenant_id = 1 LIMIT 1;
SELECT @blog_category_id := id FROM cms_category WHERE name = 'Blog' AND tenant_id = 1 LIMIT 1;
SELECT @casestudies_category_id := id FROM cms_category WHERE name = 'Case Studies' AND tenant_id = 1 LIMIT 1;
SELECT @changelog_category_id := id FROM cms_category WHERE name = 'Changelog' AND tenant_id = 1 LIMIT 1;

-- Articles for ImageDiff category
INSERT INTO cms_article (title, slug, content, content_type, excerpt, author_id, status, is_featured, is_pinned, allow_comment, visibility, password, created_at, updated_at, published_at, cover_image, template, sort_order, tenant_id)
VALUES 
('ImageDiff Pro: Complete Guide to Image Comparison', 'imagediff-pro-complete-guide', 'This comprehensive guide explains everything you need to know about using ImageDiff Pro for professional image comparison. Learn advanced techniques and best practices for detecting differences between images with precision and accuracy.', 'markdown', 'Learn how to use ImageDiff Pro with this comprehensive guide covering all features and techniques.', 1, 'published', TRUE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('5 Ways ImageDiff Improves Design Quality Control', 'imagediff-design-quality-control', 'Discover how ImageDiff technology can significantly improve your design quality control process. This article showcases 5 practical applications to streamline your workflow and catch visual discrepancies before they reach production.', 'markdown', 'Discover 5 practical ways ImageDiff technology can revolutionize your design quality control processes.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('ImageDiff API Documentation and Integration Guide', 'imagediff-api-documentation', 'Complete technical documentation for integrating the ImageDiff API into your applications. Includes authentication methods, endpoint references, request/response formats, and code samples in multiple programming languages.', 'markdown', 'Technical guide for developers looking to integrate ImageDiff capabilities into their applications.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('Comparing ImageDiff with Other Visual Testing Tools', 'imagediff-vs-competitors', 'An objective comparison between ImageDiff and other leading visual testing tools available in the market. Analyze features, performance metrics, pricing, and suitability for different use cases to make an informed decision.', 'markdown', 'Comprehensive comparison of ImageDiff against competitors to help you choose the right visual testing solution.', 1, 'published', FALSE, TRUE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('Automating UI Testing with ImageDiff and CI/CD Pipelines', 'imagediff-cicd-automation', 'Learn how to integrate ImageDiff into your continuous integration and delivery pipelines to automate visual regression testing. Step-by-step instructions for popular CI/CD platforms including Jenkins, GitHub Actions, and GitLab CI.', 'markdown', 'Step-by-step guide to automating visual regression testing with ImageDiff in CI/CD environments.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('ImageDiff Enterprise: Features for Large Organizations', 'imagediff-enterprise-features', 'Explore the enterprise-grade features of ImageDiff designed specifically for large organizations. Learn about team collaboration tools, advanced security controls, custom reporting, and scalability options.', 'markdown', 'Overview of ImageDiff Enterprise features designed for large-scale organizational deployment.', 1, 'published', TRUE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('Mastering Pixel-Perfect Comparisons with ImageDiff', 'mastering-pixel-perfect-imagediff', 'Advanced techniques for achieving pixel-perfect comparisons using ImageDiff. This deep dive covers tolerance settings, mask regions, dynamic content handling, and other expert-level configurations.', 'markdown', 'Advanced guide to configuring ImageDiff for the most accurate pixel-perfect image comparisons.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('ImageDiff for E-commerce: Ensuring Product Visual Consistency', 'imagediff-ecommerce-applications', 'How e-commerce businesses can leverage ImageDiff to maintain consistent product imagery across thousands of listings. Includes case studies and real-world implementation strategies for online retailers.', 'markdown', 'Specialized guide for e-commerce businesses using ImageDiff to maintain visual consistency across product catalogs.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('What\'s New in ImageDiff 2023: Feature Overview', 'imagediff-2023-new-features', 'Comprehensive overview of the latest features, improvements, and bug fixes in the 2023 release of ImageDiff. Learn about AI-powered difference detection, improved cloud integration, and enhanced reporting capabilities.', 'markdown', 'Detailed rundown of all new features and improvements in the latest ImageDiff 2023 release.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1);

-- Articles for Free Tools category
INSERT INTO cms_article (title, slug, content, content_type, excerpt, author_id, status, is_featured, is_pinned, allow_comment, visibility, password, created_at, updated_at, published_at, cover_image, template, sort_order, tenant_id)
VALUES 
('10 Essential Free Tools for Web Developers', 'essential-free-developer-tools', 'Discover our handpicked selection of free tools that every web developer should have in their toolkit. From code editors to debugging utilities, these resources will help streamline your development workflow without costing a penny.', 'markdown', 'Curated list of must-have free tools for web developers to boost productivity and efficiency.', 1, 'published', TRUE, TRUE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('Free Color Palette Generator: Create Perfect Color Schemes', 'free-color-palette-generator', 'Introduction to our free color palette generator tool. Learn how to create harmonious color schemes for your designs, export in various formats, and integrate with popular design applications.', 'markdown', 'Guide to using our free color palette generator to create professional color schemes for your projects.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('Responsive Design Tester: Test Your Website Across Devices', 'responsive-design-testing-tool', 'Step-by-step tutorial for using our free responsive design testing tool. Check how your website looks and functions across various screen sizes and devices without needing physical hardware.', 'markdown', 'Learn to use our free tool for testing website responsiveness across multiple device profiles.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('SEO Analyzer Tool: Optimize Your Website for Search Engines', 'free-seo-analyzer-tool', 'Comprehensive guide to our free SEO analyzer tool. Discover how to identify and fix common SEO issues, improve your search engine rankings, and attract more organic traffic to your website.', 'markdown', 'Complete walkthrough of our free SEO analysis tool to help improve your website\'s search engine performance.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('Free Performance Benchmarking Tool for Web Applications', 'web-performance-benchmarking-tool', 'Introduction to our free web performance benchmarking tool. Learn how to measure loading speeds, identify bottlenecks, and optimize your web application for better user experience and higher conversion rates.', 'markdown', 'Guide to using our free performance testing tool to identify and fix website speed issues.', 1, 'published', TRUE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('Privacy Policy Generator: Create Compliant Policies Easily', 'free-privacy-policy-generator', 'Tutorial for our free privacy policy generator tool. Create legally compliant privacy policies for your website or application in minutes, with customization options for different jurisdictions and business types.', 'markdown', 'Learn how to quickly generate compliant privacy policies with our free tool.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('Free Accessibility Checker: Make Your Website Inclusive', 'website-accessibility-checker', 'Guide to using our free accessibility checking tool. Learn how to identify accessibility issues on your website, understand WCAG guidelines, and implement improvements to make your content available to everyone.', 'markdown', 'How to use our accessibility checker to ensure your website meets inclusion standards.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('Code Beautifier and Formatter: Clean Up Your Code', 'free-code-beautifier-tool', 'Introduction to our free code beautifying and formatting tool. Support for multiple programming languages, customizable formatting rules, and integration options for popular IDEs and text editors.', 'markdown', 'Guide to using our code formatting tool to maintain consistent code style across your projects.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('Free SSL Checker Tool: Verify Your Website Security', 'ssl-certificate-checker-tool', 'Tutorial for our free SSL certificate checking tool. Learn how to verify your SSL configuration, identify security vulnerabilities, and ensure your website meets modern encryption standards.', 'markdown', 'Learn to verify and troubleshoot your website\'s SSL security configuration with our free checking tool.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1);

-- Articles for Affiliate category
INSERT INTO cms_article (title, slug, content, content_type, excerpt, author_id, status, is_featured, is_pinned, allow_comment, visibility, password, created_at, updated_at, published_at, cover_image, template, sort_order, tenant_id)
VALUES 
('Getting Started with Our Affiliate Program: Complete Guide', 'affiliate-program-getting-started', 'Everything you need to know about joining and succeeding in our affiliate program. Learn about commission structures, promotional materials, tracking systems, and payout methods to maximize your affiliate revenue.', 'markdown', 'Comprehensive guide to joining and succeeding in our affiliate marketing program.', 1, 'published', TRUE, TRUE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('Top 10 Affiliate Marketing Strategies That Actually Work', 'top-affiliate-marketing-strategies', 'Discover proven affiliate marketing strategies that consistently deliver results. From content marketing to social media promotion, learn actionable techniques to increase your conversion rates and commission earnings.', 'markdown', 'Proven affiliate marketing strategies to boost your conversion rates and commission earnings.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('Affiliate Marketing for Beginners: Terms and Concepts', 'affiliate-marketing-beginners-guide', 'A comprehensive introduction to affiliate marketing terminology and fundamental concepts. Perfect for beginners who want to understand tracking links, cookies, conversion rates, and other essential aspects of affiliate programs.', 'markdown', 'Introduction to affiliate marketing terminology and concepts for newcomers to the industry.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('How to Create High-Converting Affiliate Content', 'create-high-converting-affiliate-content', 'Learn the art of creating content that drives affiliate conversions. This article covers persuasive writing techniques, effective call-to-actions, trust building elements, and content formats that maximize click-through rates.', 'markdown', 'Guide to creating compelling content that drives higher conversion rates for affiliate products.', 1, 'published', TRUE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('Affiliate Link Disclosure: Legal Requirements Explained', 'affiliate-link-disclosure-requirements', 'Understanding the legal obligations for disclosing affiliate relationships to your audience. Learn about FTC guidelines, international regulations, and best practices for transparent affiliate marketing that builds trust.', 'markdown', 'Explanation of legal requirements and best practices for proper affiliate link disclosure.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('Advanced Affiliate Analytics: Tracking Performance Metrics', 'affiliate-analytics-performance-tracking', 'Deep dive into tracking and analyzing your affiliate marketing performance. Learn which metrics matter most, how to set up advanced tracking, and how to use data insights to optimize your promotional strategies.', 'markdown', 'Advanced guide to tracking and analyzing affiliate marketing performance metrics.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('Seasonal Affiliate Marketing: Maximizing Holiday Sales', 'seasonal-affiliate-marketing-strategies', 'Strategies for capitalizing on seasonal trends and holiday shopping periods in your affiliate marketing campaigns. Includes planning timelines, promotional ideas, and tips for standing out during competitive sales seasons.', 'markdown', 'Strategic guide to planning and executing successful seasonal affiliate marketing campaigns.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('Affiliate Marketing and SEO: Ranking Your Promotional Content', 'affiliate-marketing-seo-strategies', 'Learn how to optimize your affiliate content for search engines while maintaining quality and compliance. This guide covers keyword research, on-page SEO tactics, and link building strategies specific to affiliate marketers.', 'markdown', 'SEO techniques specifically tailored for affiliate marketers to improve content visibility and rankings.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('Affiliate Program Commission Tiers and Bonus Structure', 'affiliate-commission-tiers-explanation', 'Detailed explanation of our affiliate program\'s commission structure, including performance tiers, bonuses, and special incentives. Learn how to progress to higher commission levels and maximize your earnings.', 'markdown', 'Complete breakdown of our affiliate program commission tiers, bonuses, and earning potential.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1);

-- Articles for Blog category
INSERT INTO cms_article (title, slug, content, content_type, excerpt, author_id, status, is_featured, is_pinned, allow_comment, visibility, password, created_at, updated_at, published_at, cover_image, template, sort_order, tenant_id)
VALUES 
('The Future of Visual Testing in Software Development', 'future-of-visual-testing', 'Exploring emerging trends and technologies in visual testing for software applications. From AI-powered analysis to integration with design systems, discover how visual testing is evolving to meet the demands of modern development workflows.', 'markdown', 'In-depth look at emerging trends and technologies shaping the future of visual testing.', 1, 'published', TRUE, TRUE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('How to Build a Culture of Quality in Development Teams', 'building-quality-culture-dev-teams', 'Practical strategies for fostering a quality-first mindset in software development teams. Learn how to implement effective quality assurance processes, encourage ownership, and measure the impact of quality initiatives.', 'markdown', 'Strategies for creating and nurturing a quality-focused culture in development organizations.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('Accessibility Testing: Why It Matters and How to Do It Right', 'accessibility-testing-importance-guide', 'Comprehensive guide to accessibility testing for digital products. Learn why accessibility is essential for inclusive design, how to conduct effective testing, and how to remediate common accessibility issues.', 'markdown', 'Importance of accessibility testing and practical methods for implementation in your projects.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('Optimizing Web Performance: Tips for Faster Loading Times', 'web-performance-optimization-tips', 'Practical techniques for improving web application performance and loading speed. From image optimization to code splitting, discover actionable steps to enhance user experience and boost conversion rates through better performance.', 'markdown', 'Actionable strategies to improve website loading times and overall performance metrics.', 1, 'published', TRUE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('The Psychology of User Experience: Design Principles That Work', 'psychology-ux-design-principles', 'Exploring the psychological principles that influence effective user experience design. Learn how cognitive biases, perception patterns, and emotional responses affect user behavior and how to apply this knowledge to your designs.', 'markdown', 'How psychological principles can inform better UX design decisions for digital products.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('DevOps and QA: Bridging the Gap for Seamless Delivery', 'devops-qa-integration-guide', 'Strategies for integrating quality assurance practices into DevOps workflows. Discover how to automate testing, maintain quality in rapid deployment cycles, and foster collaboration between development and QA teams.', 'markdown', 'How to successfully integrate QA practices into DevOps workflows for better quality outcomes.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('Design Systems: Building Consistent User Experiences at Scale', 'design-systems-consistent-ux', 'Comprehensive guide to creating and implementing effective design systems. Learn how to establish component libraries, documentation standards, and governance processes that ensure consistent user experiences across large applications.', 'markdown', 'Guide to implementing design systems for maintaining consistency across complex applications.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('AI in Software Testing: Current Applications and Future Potential', 'ai-software-testing-applications', 'Exploring how artificial intelligence is transforming software testing practices. From automated test generation to intelligent test prioritization, learn about current AI applications and future possibilities in quality assurance.', 'markdown', 'Current and emerging applications of artificial intelligence in software testing processes.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('Cross-Browser Testing Strategies for Modern Web Applications', 'cross-browser-testing-strategies', 'Practical approaches to ensuring your web applications work consistently across different browsers and devices. Learn about testing tools, common compatibility issues, and efficient workflows for cross-browser quality assurance.', 'markdown', 'Effective strategies for testing and ensuring web application compatibility across different browsers.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1);

-- Articles for Case Studies category
INSERT INTO cms_article (title, slug, content, content_type, excerpt, author_id, status, is_featured, is_pinned, allow_comment, visibility, password, created_at, updated_at, published_at, cover_image, template, sort_order, tenant_id)
VALUES 
('How TechGiant Reduced UI Bugs by 87% with Visual Testing', 'techgiant-reduced-ui-bugs-case-study', 'Detailed case study of how TechGiant, a leading SaaS provider, implemented visual testing into their workflow and dramatically reduced UI-related bugs in production. Includes implementation strategy, challenges overcome, and measurable results.', 'markdown', 'Case study showing how TechGiant dramatically reduced UI bugs through automated visual testing.', 1, 'published', TRUE, TRUE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('E-commerce Platform Increases Conversion Rate After Visual Overhaul', 'ecommerce-conversion-rate-case-study', 'How a major e-commerce platform used visual testing to identify and fix inconsistencies in their checkout flow, resulting in a 23% increase in conversion rates. Explore their methodology, tools used, and lessons learned.', 'markdown', 'How an e-commerce company boosted conversions by fixing visual inconsistencies in their user journey.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('Banking App Achieves Zero Defect Releases with Automated Testing', 'banking-app-zero-defect-case-study', 'Case study of a financial institution that implemented comprehensive automated testing, including visual checks, to achieve zero-defect releases for their mobile banking application. Details their testing architecture, tools, and processes.', 'markdown', 'How a banking app implemented a robust testing strategy to achieve defect-free releases.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('Healthcare Provider Improves Accessibility Compliance by 95%', 'healthcare-accessibility-compliance-case-study', 'How a national healthcare provider used automated accessibility testing to identify and remediate compliance issues across their patient portal, improving their WCAG compliance score from 42% to 98% in six months.', 'markdown', 'Case study of a healthcare provider\'s journey to achieve near-perfect accessibility compliance.', 1, 'published', TRUE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('Global Media Company Cuts Testing Time by 75% with AI Tools', 'media-company-testing-automation-case-study', 'Detailed analysis of how a global media conglomerate implemented AI-powered testing tools to automate repetitive test cases, reducing their QA cycle time by 75% while maintaining quality standards across multiple platforms.', 'markdown', 'How a media company used AI-powered tools to dramatically reduce their testing timelines.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('Retail Giant\'s Journey to Continuous Visual Testing', 'retail-continuous-visual-testing-case-study', 'Case study of a major retail corporation\'s two-year journey to implement continuous visual testing across their e-commerce platform, mobile apps, and in-store digital experiences. Includes ROI analysis and key success factors.', 'markdown', 'A retail corporation\'s implementation strategy for continuous visual testing across multiple channels.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('Travel Booking Platform Reduces Support Tickets with Better UI Testing', 'travel-booking-ui-testing-case-study', 'How a travel booking service identified that 40% of their customer support tickets stemmed from UI inconsistencies, and implemented a comprehensive visual testing strategy that reduced support volume by 35% in the first quarter.', 'markdown', 'Case study showing how improved UI testing significantly reduced customer support inquiries.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('Gaming Studio Maintains Visual Consistency Across 15 Platforms', 'gaming-studio-visual-consistency-case-study', 'Case study of how a major gaming studio ensures visual consistency for their titles across 15 different platforms and device types, using a combination of automated visual testing and a unified design system.', 'markdown', 'How a gaming company maintains consistent visuals across multiple platforms and device types.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('B2B Software Vendor\'s Quality Transformation Journey', 'b2b-software-quality-transformation-case-study', 'Comprehensive case study of a B2B software vendor\'s 18-month quality transformation initiative, which included implementing visual testing, automated regression testing, and a shift-left testing approach. Includes before/after metrics and ROI analysis.', 'markdown', 'Detailed journey of a B2B software company\'s complete quality assurance transformation.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1);

-- Articles for Changelog category
INSERT INTO cms_article (title, slug, content, content_type, excerpt, author_id, status, is_featured, is_pinned, allow_comment, visibility, password, created_at, updated_at, published_at, cover_image, template, sort_order, tenant_id)
VALUES 
('Product Release 4.5: AI-Powered Visual Analysis Engine', 'product-release-4-5-ai-visual-analysis', 'Announcing the release of version 4.5, featuring our revolutionary AI-powered visual analysis engine. This update brings significant improvements to difference detection accuracy, false positive reduction, and processing speed for large image sets.', 'markdown', 'Details of our 4.5 release featuring the new AI-powered visual analysis capabilities.', 1, 'published', TRUE, TRUE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('March 2023 Update: Enhanced Cloud Integration and Storage Options', 'march-2023-update-cloud-integration', 'Overview of our March 2023 update featuring enhanced cloud integration with major providers (AWS, Azure, GCP), improved artifact storage options, and new data retention policies to help manage your testing assets more efficiently.', 'markdown', 'Summary of March 2023 update focusing on cloud integration improvements and storage options.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('Security Update 2023.2: Enhanced Authentication and Permissions', 'security-update-2023-2', 'Critical security update 2023.2 introduces enhanced authentication mechanisms, fine-grained permission controls, and improved audit logging. All users are strongly encouraged to update to this version as soon as possible.', 'markdown', 'Details of security update 2023.2 with important authentication and permission enhancements.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('New Feature: Custom Comparison Algorithms for Specialized Industries', 'custom-comparison-algorithms-feature', 'Introducing custom comparison algorithms tailored for specialized industries including medical imaging, satellite imagery, and print production. These new algorithms provide industry-specific sensitivity and accuracy for your visual testing needs.', 'markdown', 'Announcement of new industry-specific comparison algorithms for specialized visual testing needs.', 1, 'published', TRUE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('Performance Optimization Update: 60% Faster Processing Times', 'performance-optimization-update', 'This update brings significant performance improvements to our core processing engine, resulting in up to 60% faster comparison times for most image types. Additional optimizations include reduced memory usage and improved parallel processing capabilities.', 'markdown', 'Details of our performance optimization update delivering significantly faster processing times.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('API v2.0: New Endpoints and Comprehensive Documentation', 'api-v2-0-release-documentation', 'Announcing the release of API v2.0, featuring new endpoints for batch processing, enhanced webhook integrations, and improved error handling. This version includes backward compatibility with v1.x APIs and comprehensive migration documentation.', 'markdown', 'Announcement of API v2.0 with details on new features and backward compatibility.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('Mobile SDK Update: Now Supporting React Native and Flutter', 'mobile-sdk-react-native-flutter-support', 'Our mobile SDK has been updated to include official support for React Native and Flutter frameworks. This update enables seamless integration of our visual testing capabilities into cross-platform mobile applications built with these technologies.', 'markdown', 'Details of mobile SDK update adding official support for React Native and Flutter applications.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('Enterprise Edition 3.0: Advanced Team Collaboration Features', 'enterprise-edition-3-0-team-collaboration', 'Announcing Enterprise Edition 3.0, featuring advanced team collaboration capabilities including role-based dashboards, enhanced reporting, cross-team test sharing, and integrated approval workflows for large organizations with multiple testing teams.', 'markdown', 'Overview of Enterprise Edition 3.0 with focus on enhanced team collaboration features.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1),
('Deprecation Notice: Legacy Comparison Engine End-of-Support Timeline', 'legacy-comparison-engine-deprecation-notice', 'Important notice about the deprecation schedule for our legacy comparison engine. Learn about the timeline, migration paths to our modern engine, and support options for customers with special requirements or constraints.', 'markdown', 'Deprecation timeline and migration information for users of the legacy comparison engine.', 1, 'published', FALSE, FALSE, TRUE, 'public', NULL, @now, @now, @now, @cover_image, NULL, 0, 1);

-- Now create the relationships between articles and categories in the ArticleCategory table
-- For ImageDiff category articles
INSERT INTO cms_article_category (article_id, category_id, created_at, tenant_id)
SELECT id, @imagediff_category_id, @now, 1 FROM cms_article 
WHERE slug LIKE 'imagediff%' AND tenant_id = 1;

-- For Free Tools category articles
INSERT INTO cms_article_category (article_id, category_id, created_at, tenant_id)
SELECT id, @freetools_category_id, @now, 1 FROM cms_article 
WHERE (slug LIKE '%tool%' OR slug LIKE 'free-%') AND tenant_id = 1 AND slug NOT LIKE 'imagediff%';

-- For Affiliate category articles
INSERT INTO cms_article_category (article_id, category_id, created_at, tenant_id)
SELECT id, @affiliate_category_id, @now, 1 FROM cms_article 
WHERE slug LIKE 'affiliate%' AND tenant_id = 1;

-- For Blog category articles
INSERT INTO cms_article_category (article_id, category_id, created_at, tenant_id)
SELECT id, @blog_category_id, @now, 1 FROM cms_article 
WHERE (slug LIKE 'future-%' OR slug LIKE 'building-%' OR slug LIKE 'accessibility-%' OR 
      slug LIKE 'web-performance%' OR slug LIKE 'psychology-%' OR slug LIKE 'devops-%' OR
      slug LIKE 'design-systems%' OR slug LIKE 'ai-software%' OR slug LIKE 'cross-browser%') AND tenant_id = 1;

-- For Case Studies category articles
INSERT INTO cms_article_category (article_id, category_id, created_at, tenant_id)
SELECT id, @casestudies_category_id, @now, 1 FROM cms_article 
WHERE slug LIKE '%-case-study' AND tenant_id = 1;

-- For Changelog category articles
INSERT INTO cms_article_category (article_id, category_id, created_at, tenant_id)
SELECT id, @changelog_category_id, @now, 1 FROM cms_article 
WHERE (slug LIKE 'product-release%' OR slug LIKE '%-update-%' OR 
      slug LIKE '%-edition-%' OR slug LIKE 'api-v%' OR 
      slug LIKE '%-notice%' OR slug LIKE '%-feature') AND tenant_id = 1;

-- Create article statistics records for all articles
INSERT INTO cms_article_statistics (article_id, views_count, unique_views_count, likes_count, dislikes_count, comments_count, shares_count, bookmarks_count, avg_reading_time, bounce_rate, last_updated_at, tenant_id)
SELECT id, FLOOR(RAND() * 1000), FLOOR(RAND() * 800), FLOOR(RAND() * 100), FLOOR(RAND() * 10), FLOOR(RAND() * 50), FLOOR(RAND() * 30), FLOOR(RAND() * 20), FLOOR(RAND() * 300) + 60, RAND() * 100, @now, 1
FROM cms_article WHERE tenant_id = 1;

-- Create article metadata for all articles
INSERT INTO cms_article_meta (article_id, seo_title, seo_description, seo_keywords, og_title, og_description, og_image, created_at, updated_at, tenant_id)
SELECT 
  id, 
  title, 
  SUBSTRING(excerpt, 1, 160), 
  CONCAT(SUBSTRING_INDEX(slug, '-', 1), ', ', SUBSTRING_INDEX(slug, '-', 2), ', ', SUBSTRING_INDEX(slug, '-', -1)), 
  title, 
  SUBSTRING(excerpt, 1, 100),
  cover_image, 
  @now, 
  @now, 
  1
FROM cms_article WHERE tenant_id = 1; 