# Generated by Django 5.2 on 2025-06-15 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='如：user:create', max_length=100, unique=True, verbose_name='权限代码')),
                ('name', models.CharField(help_text='如：创建用户', max_length=100, verbose_name='权限名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='权限描述')),
                ('category', models.CharField(help_text='如：用户管理、内容管理等', max_length=50, verbose_name='权限分类')),
                ('is_system', models.BooleanField(default=False, help_text='系统权限不允许删除', verbose_name='是否系统权限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'db_table': 'rbac_permission',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='角色名称')),
                ('code', models.CharField(help_text='用于API和代码中引用', max_length=50, verbose_name='角色代码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='角色描述')),
                ('is_system', models.BooleanField(default=False, help_text='系统角色不允许删除', verbose_name='是否系统角色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tenant', models.ForeignKey(blank=True, help_text='为空表示系统角色，所有租户可见', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='tenants.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'rbac_role',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'tenant')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='rbac.permission', verbose_name='权限')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='rbac.role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '角色权限',
                'verbose_name_plural': '角色权限',
                'db_table': 'rbac_role_permission',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('user', '管理员'), ('member', '普通成员')], max_length=10, verbose_name='用户类型')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('is_active', models.BooleanField(default=True, help_text='可临时禁用角色', verbose_name='是否激活')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='生效开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='生效结束日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='rbac.role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '用户角色',
                'verbose_name_plural': '用户角色',
                'db_table': 'rbac_user_role',
                'unique_together': {('user_type', 'user_id', 'role')},
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', through='rbac.RolePermission', to='rbac.permission', verbose_name='权限'),
        ),
    ]
