# Generated by Django 5.2 on 2025-04-27 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_tenant_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类型名称')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='类型描述')),
                ('is_system', models.BooleanField(default=False, verbose_name='是否系统预设')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='图标')),
                ('translations', models.JSONField(blank=True, default=dict, verbose_name='多语言翻译')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_categories', to='tenants.tenant', verbose_name='所属租户')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_categories', to=settings.AUTH_USER_MODEL, verbose_name='创建用户')),
            ],
            options={
                'verbose_name': '打卡类型',
                'verbose_name_plural': '打卡类型',
                'db_table': 'task_category',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'user', 'tenant')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('status', models.CharField(choices=[('active', '进行中'), ('completed', '已完成'), ('paused', '已暂停'), ('archived', '已归档')], default='active', max_length=20, verbose_name='状态')),
                ('reminder', models.BooleanField(default=False, verbose_name='是否启用提醒')),
                ('reminder_time', models.TimeField(blank=True, null=True, verbose_name='提醒时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tenants.tenant', verbose_name='所属租户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='check_system.taskcategory', verbose_name='所属类型')),
            ],
            options={
                'verbose_name': '打卡任务',
                'verbose_name_plural': '打卡任务',
                'db_table': 'task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, verbose_name='模板描述')),
                ('is_system', models.BooleanField(default=False, verbose_name='是否系统预设')),
                ('translations', models.JSONField(blank=True, default=dict, verbose_name='多语言翻译')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='check_system.taskcategory', verbose_name='所属类型')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='tenants.tenant', verbose_name='所属租户')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to=settings.AUTH_USER_MODEL, verbose_name='创建用户')),
            ],
            options={
                'verbose_name': '任务模板',
                'verbose_name_plural': '任务模板',
                'db_table': 'task_template',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField(verbose_name='打卡日期')),
                ('check_time', models.TimeField(verbose_name='打卡时间')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_records', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_records', to='check_system.task', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '打卡记录',
                'verbose_name_plural': '打卡记录',
                'db_table': 'check_record',
                'ordering': ['-check_date', '-check_time'],
                'unique_together': {('user', 'task', 'check_date')},
            },
        ),
    ]
