# Generated by Django 5.2 on 2025-04-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='reminder',
            field=models.BooleanField(default=False, verbose_name='是否启用提醒'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True, verbose_name='提醒时间'),
        ),
    ]
