# Generated by Django 5.2 on 2026-01-13 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_system', '0001_initial'),
        ('tenants', '0002_alter_tenantquota_current_storage_used_mb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcategory',
            options={'ordering': ['sort_order', '-created_at'], 'verbose_name': '打卡类型', 'verbose_name_plural': '打卡类型'},
        ),
        migrations.AddField(
            model_name='checkrecord',
            name='delayed',
            field=models.BooleanField(default=False, verbose_name='是否拖延'),
        ),
        migrations.AddField(
            model_name='checkrecord',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='存储主题特定的打卡数据，如睡眠时间、运动记录等', verbose_name='扩展数据'),
        ),
        migrations.AddField(
            model_name='checkrecord',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_records', to='check_system.taskcategory', verbose_name='打卡主题'),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='color',
            field=models.CharField(blank=True, help_text='HEX颜色值，如 #8B5CF6', max_length=20, verbose_name='主题色'),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='form_type',
            field=models.CharField(choices=[('text', '文本输入'), ('sleep', '睡眠时间'), ('exercise', '运动记录'), ('reading', '阅读记录'), ('mood', '情绪管理'), ('finance', '理财记录'), ('work', '工作效率')], default='text', max_length=20, verbose_name='表单类型'),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='goal',
            field=models.TextField(blank=True, verbose_name='主题目标'),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='quote',
            field=models.CharField(blank=True, max_length=200, verbose_name='名言'),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='tip',
            field=models.TextField(blank=True, verbose_name='小贴士'),
        ),
        migrations.CreateModel(
            name='CheckinCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(help_text='自动设为开始日期+20天', verbose_name='结束日期')),
                ('selected_themes', models.JSONField(default=list, help_text='选择的主题ID列表', verbose_name='选择的主题')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkin_cycles', to='tenants.tenant', verbose_name='所属租户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_cycles', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '打卡周期',
                'verbose_name_plural': '打卡周期',
                'db_table': 'checkin_cycle',
                'ordering': ['-created_at'],
            },
        ),
    ]
