# Generated by Django 5.2 on 2025-04-30 09:00

from django.db import migrations


def delete_records_without_tenant(apps, schema_editor):
    """
    删除租户字段为空的数据
    """
    # 获取模型引用
    TaskCategory = apps.get_model('check_system', 'TaskCategory')
    TaskTemplate = apps.get_model('check_system', 'TaskTemplate')
    Task = apps.get_model('check_system', 'Task')
    
    # 删除TaskCategory中tenant为空的记录
    deleted_count = TaskCategory.objects.filter(tenant__isnull=True).delete()[0]
    print(f"Deleted {deleted_count} TaskCategory records without tenant")
    
    # 删除TaskTemplate中tenant为空的记录
    deleted_count = TaskTemplate.objects.filter(tenant__isnull=True).delete()[0]
    print(f"Deleted {deleted_count} TaskTemplate records without tenant")
    
    # 删除Task中tenant为空的记录
    deleted_count = Task.objects.filter(tenant__isnull=True).delete()[0]
    print(f"Deleted {deleted_count} Task records without tenant")


class Migration(migrations.Migration):

    dependencies = [
        ('check_system', '0002_tasktemplate_reminder_tasktemplate_reminder_time'),
    ]

    operations = [
        migrations.RunPython(delete_records_without_tenant, migrations.RunPython.noop),
    ]
