# Generated by Django 5.2 on 2025-05-05 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_system', '0003_delete_records_without_tenant'),
        ('tenants', '0002_tenant_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='frequency_days',
            field=models.JSONField(blank=True, default=list, verbose_name='打卡频率天数'),
        ),
        migrations.AddField(
            model_name='task',
            name='frequency_type',
            field=models.CharField(choices=[('daily', '每天'), ('weekly', '每周'), ('monthly', '每月'), ('custom', '自定义')], default='daily', max_length=20, verbose_name='打卡频率类型'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tenants.tenant', verbose_name='所属租户'),
        ),
    ]
