# Generated by Django 5.2 on 2025-05-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_system', '0004_add_task_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkrecord',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='评论'),
        ),
        migrations.AddField(
            model_name='checkrecord',
            name='completion_time',
            field=models.TimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='checkrecord',
            name='remarks',
            field=models.TextField(blank=True, default='', verbose_name='备注'),
        ),
    ]
