# Generated by Django 5.2 on 2026-03-23 03:14

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class AlterModelBases(Operation):
    reduces_to_sql = False
    reversible = True

    def __init__(self, name, bases, reverse_bases):
        self.name = name
        self.bases = bases
        self.reverse_bases = reverse_bases

    def state_forwards(self, app_label, state):
        model_key = (app_label, self.name.lower())
        state.models[model_key].bases = self.bases
        state.reload_model(app_label, self.name.lower(), delay=False)

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        pass

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        pass

    def describe(self):
        return f"Alter bases for {self.name}"

    @property
    def migration_name_fragment(self):
        return f"alter_{self.name.lower()}_bases"


def _index_exists(cursor, table_name, index_name):
    cursor.execute(
        """
        SELECT COUNT(*)
        FROM information_schema.statistics
        WHERE table_schema = DATABASE()
          AND table_name = %s
          AND index_name = %s
        """,
        [table_name, index_name],
    )
    return bool(cursor.fetchone()[0])


def _column_exists(cursor, table_name, column_name):
    cursor.execute(
        """
        SELECT COUNT(*)
        FROM information_schema.columns
        WHERE table_schema = DATABASE()
          AND table_name = %s
          AND column_name = %s
        """,
        [table_name, column_name],
    )
    return bool(cursor.fetchone()[0])


def sync_check_system_schema(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        if _index_exists(cursor, 'task_category', 'task_category_name_user_id_tenant_id_99ca8fa4_uniq'):
            schema_editor.execute(
                'ALTER TABLE `task_category` DROP INDEX `task_category_name_user_id_tenant_id_99ca8fa4_uniq`'
            )

        for table_name in ['task', 'check_record', 'checkin_cycle', 'task_template']:
            for column_name in ['created_at', 'updated_at']:
                if _column_exists(cursor, table_name, column_name):
                    schema_editor.execute(
                        f'ALTER TABLE `{table_name}` MODIFY COLUMN `{column_name}` datetime(6) NULL'
                    )

        for table_name in ['task', 'check_record', 'checkin_cycle']:
            if _column_exists(cursor, table_name, 'member_id'):
                schema_editor.execute(
                    f'ALTER TABLE `{table_name}` MODIFY COLUMN `member_id` bigint NOT NULL'
                )

        for table_name, column_name, index_name in [
            ('task', 'created_at', 'task_created_at_2269bec0'),
            ('task', 'updated_at', 'task_updated_at_91ef894e'),
            ('check_record', 'created_at', 'check_record_created_at_dabe5d05'),
            ('check_record', 'updated_at', 'check_record_updated_at_idx'),
            ('checkin_cycle', 'created_at', 'checkin_cycle_created_at_29ffd47f'),
            ('checkin_cycle', 'updated_at', 'checkin_cycle_updated_at_2d1e2b51'),
            ('task_template', 'created_at', 'task_template_created_at_idx'),
            ('task_template', 'updated_at', 'task_template_updated_at_idx'),
        ]:
            if _column_exists(cursor, table_name, column_name) and not _index_exists(cursor, table_name, index_name):
                schema_editor.execute(
                    f'CREATE INDEX `{index_name}` ON `{table_name}` (`{column_name}`)'
                )


class Migration(migrations.Migration):

    dependencies = [
        ('check_system', '0004_convert_to_translatable_model'),
        ('tenants', '0002_alter_tenantquota_current_storage_used_mb'),
        ('users', '0004_remove_member_max_trial_licenses'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(sync_check_system_schema, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='taskcategory',
                    unique_together=set(),
                ),
                migrations.AddField(
                    model_name='checkrecord',
                    name='tenant',
                    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='租户'),
                ),
                migrations.AlterField(
                    model_name='checkincycle',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间'),
                ),
                migrations.AlterField(
                    model_name='checkincycle',
                    name='member',
                    field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='checkin_cycles', to='users.member', verbose_name='所属成员'),
                    preserve_default=False,
                ),
                migrations.AlterField(
                    model_name='checkincycle',
                    name='tenant',
                    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='租户'),
                ),
                migrations.AlterField(
                    model_name='checkincycle',
                    name='updated_at',
                    field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间'),
                ),
                migrations.AlterField(
                    model_name='checkrecord',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间'),
                ),
                migrations.AlterField(
                    model_name='checkrecord',
                    name='member',
                    field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='check_records', to='users.member', verbose_name='所属成员'),
                    preserve_default=False,
                ),
                migrations.AlterField(
                    model_name='task',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间'),
                ),
                migrations.AlterField(
                    model_name='task',
                    name='member',
                    field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.member', verbose_name='所属成员'),
                    preserve_default=False,
                ),
                migrations.AlterField(
                    model_name='task',
                    name='tenant',
                    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='租户'),
                ),
                migrations.AlterField(
                    model_name='task',
                    name='updated_at',
                    field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间'),
                ),
                migrations.AlterField(
                    model_name='taskcategory',
                    name='tenant',
                    field=models.ForeignKey(blank=True, help_text='系统预设主题的tenant为NULL', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_categories', to='tenants.tenant', verbose_name='所属租户'),
                ),
                AlterModelBases(
                    name='TaskCategory',
                    bases=(parler.models.TranslatableModel,),
                    reverse_bases=(models.Model,),
                ),
                migrations.AlterField(
                    model_name='taskcategorytranslation',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='taskcategorytranslation',
                    name='master',
                    field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='check_system.taskcategory'),
                ),
                migrations.AlterField(
                    model_name='tasktemplate',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间'),
                ),
                migrations.AlterField(
                    model_name='tasktemplate',
                    name='tenant',
                    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='租户'),
                ),
                migrations.AlterField(
                    model_name='tasktemplate',
                    name='updated_at',
                    field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间'),
                ),
            ],
        ),
    ]
