# Generated by Django 5.2 on 2025-07-16 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='路由名称')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='唯一标识符')),
                ('path', models.CharField(max_length=200, verbose_name='路由路径')),
                ('component', models.CharField(blank=True, max_length=200, null=True, verbose_name='前端组件路径')),
                ('redirect', models.CharField(blank=True, max_length=200, null=True, verbose_name='重定向路径')),
                ('title', models.CharField(max_length=100, verbose_name='菜单标题')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='图标名称')),
                ('extra_icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='额外图标')),
                ('rank', models.IntegerField(default=0, verbose_name='菜单排序')),
                ('show_link', models.BooleanField(default=True, verbose_name='是否在菜单中显示')),
                ('show_parent', models.BooleanField(default=True, verbose_name='是否显示父级菜单')),
                ('roles', models.JSONField(blank=True, default=list, null=True, verbose_name='页面级别权限设置')),
                ('auths', models.JSONField(blank=True, default=list, null=True, verbose_name='按钮级别权限设置')),
                ('keep_alive', models.BooleanField(default=False, verbose_name='是否缓存路由页面')),
                ('frame_src', models.CharField(blank=True, max_length=255, null=True, verbose_name='iframe链接地址')),
                ('frame_loading', models.BooleanField(default=True, verbose_name='iframe是否开启首次加载动画')),
                ('hidden_tag', models.BooleanField(default=False, verbose_name='禁止添加到标签页')),
                ('dynamic_level', models.IntegerField(blank=True, null=True, verbose_name='标签页最大数量')),
                ('active_path', models.CharField(blank=True, max_length=200, null=True, verbose_name='激活菜单的路径')),
                ('transition_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='页面动画名称')),
                ('enter_transition', models.CharField(blank=True, max_length=100, null=True, verbose_name='进场动画')),
                ('leave_transition', models.CharField(blank=True, max_length=100, null=True, verbose_name='离场动画')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menus.menu', verbose_name='父菜单')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'db_table': 'menu',
                'ordering': ['rank', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_menus', to='menus.menu', verbose_name='菜单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_menus', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户菜单',
                'verbose_name_plural': '用户菜单',
                'db_table': 'user_menu',
                'ordering': ['user', 'menu__rank'],
                'unique_together': {('user', 'menu')},
            },
        ),
    ]
