# Generated by Django 5.2 on 2025-09-05 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicensePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=100, verbose_name='方案名称')),
                ('code', models.CharField(max_length=50, verbose_name='方案代码')),
                ('plan_type', models.CharField(choices=[('trial', '试用版'), ('basic', '基础版'), ('professional', '专业版'), ('enterprise', '企业版'), ('custom', '定制版')], max_length=20, verbose_name='方案类型')),
                ('max_machines', models.PositiveIntegerField(default=1, verbose_name='最大机器数')),
                ('validity_days', models.PositiveIntegerField(default=365, verbose_name='有效天数')),
                ('features', models.JSONField(blank=True, default=dict, verbose_name='功能配置')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='价格')),
                ('currency', models.CharField(default='CNY', max_length=3, verbose_name='货币')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '禁用')], default='active', max_length=20, verbose_name='状态')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '许可证方案',
                'verbose_name_plural': '许可证方案',
                'db_table': 'licenses_license_plan',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('license_key', models.CharField(max_length=200, unique=True, verbose_name='许可证密钥')),
                ('license_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='许可证哈希')),
                ('customer_name', models.CharField(blank=True, max_length=100, verbose_name='客户名称')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='客户邮箱')),
                ('encrypted_customer_info', models.TextField(blank=True, verbose_name='加密客户信息')),
                ('max_activations', models.PositiveIntegerField(default=1, verbose_name='最大激活数')),
                ('current_activations', models.PositiveIntegerField(default=0, verbose_name='当前激活数')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='签发时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='最后验证时间')),
                ('status', models.CharField(choices=[('generated', '已生成'), ('activated', '已激活'), ('suspended', '已挂起'), ('revoked', '已撤销'), ('expired', '已过期')], default='generated', max_length=20, verbose_name='状态')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='tenants.tenant', verbose_name='租户')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='licenses.licenseplan', verbose_name='许可方案')),
            ],
            options={
                'verbose_name': '许可证',
                'verbose_name_plural': '许可证',
                'db_table': 'licenses_license',
            },
        ),
        migrations.CreateModel(
            name='MachineBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('machine_id', models.CharField(db_index=True, max_length=100, verbose_name='机器ID')),
                ('machine_fingerprint', models.CharField(db_index=True, max_length=64, verbose_name='机器指纹')),
                ('encrypted_hardware_info', models.TextField(verbose_name='加密硬件信息')),
                ('os_info', models.JSONField(default=dict, verbose_name='操作系统信息')),
                ('hardware_summary', models.JSONField(default=dict, verbose_name='硬件摘要')),
                ('last_ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='最后IP地址')),
                ('last_location', models.JSONField(blank=True, default=dict, verbose_name='最后位置')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '非活跃'), ('blocked', '已阻止')], default='active', max_length=20, verbose_name='状态')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='首次绑定时间')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='最后活跃时间')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_bindings', to='licenses.license', verbose_name='关联许可证')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '机器绑定',
                'verbose_name_plural': '机器绑定',
                'db_table': 'licenses_machine_binding',
            },
        ),
        migrations.CreateModel(
            name='LicenseUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('event_type', models.CharField(choices=[('startup', '软件启动'), ('heartbeat', '心跳检测'), ('feature_use', '功能使用'), ('shutdown', '软件关闭'), ('verification', '在线验证')], max_length=20, verbose_name='事件类型')),
                ('event_data', models.JSONField(blank=True, default=dict, verbose_name='事件数据')),
                ('software_version', models.CharField(blank=True, max_length=50, verbose_name='软件版本')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='会话ID')),
                ('cpu_usage', models.FloatField(blank=True, null=True, verbose_name='CPU使用率')),
                ('memory_usage', models.FloatField(blank=True, null=True, verbose_name='内存使用率')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间戳')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='licenses.license', verbose_name='关联许可证')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='租户')),
                ('machine_binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='licenses.machinebinding', verbose_name='机器绑定')),
            ],
            options={
                'verbose_name': '使用日志',
                'verbose_name_plural': '使用日志',
                'db_table': 'licenses_usage_log',
            },
        ),
        migrations.CreateModel(
            name='LicenseActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('activation_type', models.CharField(choices=[('online', '在线激活'), ('offline', '离线激活')], max_length=20, verbose_name='激活类型')),
                ('activation_code', models.CharField(max_length=100, unique=True, verbose_name='激活码')),
                ('client_version', models.CharField(blank=True, max_length=50, verbose_name='客户端版本')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('result', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('pending', '待处理')], default='pending', max_length=20, verbose_name='激活结果')),
                ('error_message', models.TextField(blank=True, verbose_name='错误消息')),
                ('activated_at', models.DateTimeField(auto_now_add=True, verbose_name='激活时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='licenses.license', verbose_name='关联许可证')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='租户')),
                ('machine_binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='licenses.machinebinding', verbose_name='机器绑定')),
            ],
            options={
                'verbose_name': '许可证激活',
                'verbose_name_plural': '许可证激活',
                'db_table': 'licenses_activation',
            },
        ),
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('event_type', models.CharField(choices=[('license_generated', '许可证生成'), ('license_activated', '许可证激活'), ('license_revoked', '许可证撤销'), ('keypair_generated', '密钥对生成'), ('suspicious_activity', '可疑活动'), ('authentication_failed', '认证失败'), ('privilege_escalation', '权限提升'), ('data_access', '数据访问'), ('system_change', '系统变更')], max_length=50, verbose_name='事件类型')),
                ('severity', models.CharField(choices=[('LOW', '低'), ('MEDIUM', '中'), ('HIGH', '高'), ('CRITICAL', '严重')], max_length=10, verbose_name='严重级别')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('details', models.JSONField(default=dict, verbose_name='事件详情')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间戳')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant', verbose_name='租户')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '安全审计日志',
                'verbose_name_plural': '安全审计日志',
                'db_table': 'licenses_security_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='产品代码')),
                ('description', models.TextField(blank=True, verbose_name='产品描述')),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='版本号')),
                ('public_key', models.TextField(verbose_name='RSA公钥')),
                ('private_key_hash', models.CharField(max_length=64, verbose_name='私钥哈希')),
                ('max_activations', models.PositiveIntegerField(default=5, verbose_name='最大激活数')),
                ('offline_days', models.PositiveIntegerField(default=30, verbose_name='离线允许天数')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '禁用'), ('deprecated', '已弃用')], default='active', max_length=20, verbose_name='状态')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '软件产品',
                'verbose_name_plural': '软件产品',
                'db_table': 'licenses_software_product',
            },
        ),
        migrations.AddField(
            model_name='licenseplan',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_plans', to='licenses.softwareproduct', verbose_name='关联产品'),
        ),
        migrations.AddField(
            model_name='license',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='licenses.softwareproduct', verbose_name='关联产品'),
        ),
        migrations.CreateModel(
            name='TenantLicenseQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('max_licenses', models.PositiveIntegerField(default=10, verbose_name='最大许可证数')),
                ('current_licenses', models.PositiveIntegerField(default=0, verbose_name='当前许可证数')),
                ('quota_start_date', models.DateField(verbose_name='配额开始日期')),
                ('quota_end_date', models.DateField(verbose_name='配额结束日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_quotas', to='licenses.softwareproduct', verbose_name='产品')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_quotas', to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '租户许可证配额',
                'verbose_name_plural': '租户许可证配额',
                'db_table': 'licenses_tenant_quota',
            },
        ),
        migrations.AddIndex(
            model_name='machinebinding',
            index=models.Index(fields=['license', 'status'], name='licenses_ma_license_b5ef73_idx'),
        ),
        migrations.AddIndex(
            model_name='machinebinding',
            index=models.Index(fields=['machine_fingerprint'], name='licenses_ma_machine_055807_idx'),
        ),
        migrations.AddIndex(
            model_name='machinebinding',
            index=models.Index(fields=['status', 'last_seen_at'], name='licenses_ma_status_7552c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='machinebinding',
            unique_together={('license', 'machine_fingerprint')},
        ),
        migrations.AddIndex(
            model_name='licenseusagelog',
            index=models.Index(fields=['license', 'event_type', 'timestamp'], name='licenses_us_license_f5e3ef_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseusagelog',
            index=models.Index(fields=['machine_binding', 'timestamp'], name='licenses_us_machine_41b5c8_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseusagelog',
            index=models.Index(fields=['event_type', 'timestamp'], name='licenses_us_event_t_7b48fe_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseusagelog',
            index=models.Index(fields=['timestamp'], name='licenses_us_timesta_8d92aa_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseactivation',
            index=models.Index(fields=['license', 'result'], name='licenses_ac_license_ce911a_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseactivation',
            index=models.Index(fields=['activation_code'], name='licenses_ac_activat_b9072e_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseactivation',
            index=models.Index(fields=['result', 'activated_at'], name='licenses_ac_result_13a146_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseactivation',
            index=models.Index(fields=['ip_address', 'activated_at'], name='licenses_ac_ip_addr_0d4773_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['event_type', 'timestamp'], name='licenses_se_event_t_72fb53_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['severity', 'timestamp'], name='licenses_se_severit_732b37_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['user', 'timestamp'], name='licenses_se_user_id_14f84e_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['ip_address', 'timestamp'], name='licenses_se_ip_addr_0dc8f7_idx'),
        ),
        migrations.AddIndex(
            model_name='softwareproduct',
            index=models.Index(fields=['code'], name='licenses_so_code_eb3691_idx'),
        ),
        migrations.AddIndex(
            model_name='softwareproduct',
            index=models.Index(fields=['status', 'created_at'], name='licenses_so_status_1dd4b5_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseplan',
            index=models.Index(fields=['product', 'plan_type'], name='licenses_li_product_e14b44_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseplan',
            index=models.Index(fields=['status'], name='licenses_li_status_d88c45_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='licenseplan',
            unique_together={('product', 'code')},
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['license_hash'], name='licenses_li_license_bfcbda_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['tenant', 'status'], name='licenses_li_tenant__d63aff_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['product', 'status'], name='licenses_li_product_708cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['expires_at'], name='licenses_li_expires_2124f9_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['status', 'created_at'], name='licenses_li_status_dcaf0d_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantlicensequota',
            index=models.Index(fields=['tenant', 'is_active'], name='licenses_te_tenant__d8d61b_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantlicensequota',
            index=models.Index(fields=['product', 'is_active'], name='licenses_te_product_36891f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantlicensequota',
            unique_together={('tenant', 'product')},
        ),
    ]
