# Generated by Django 5.2 on 2025-09-25 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_add_product_plan_consistency_check'),
        ('tenants', '0001_initial'),
        ('users', '0002_passwordresettoken_member_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('assignment_type', models.CharField(choices=[('direct', '直接分配'), ('inherited', '继承分配'), ('shared', '共享分配'), ('temporary', '临时分配')], default='direct', max_length=20, verbose_name='分配类型')),
                ('assignment_reason', models.TextField(blank=True, verbose_name='分配原因')),
                ('priority', models.CharField(choices=[('low', '低'), ('normal', '普通'), ('high', '高'), ('urgent', '紧急')], default='normal', max_length=10, verbose_name='优先级')),
                ('can_activate', models.BooleanField(default=True, verbose_name='允许激活')),
                ('can_deactivate', models.BooleanField(default=False, verbose_name='允许停用')),
                ('can_share', models.BooleanField(default=False, verbose_name='允许共享')),
                ('max_devices_per_user', models.PositiveIntegerField(default=1, verbose_name='用户最大设备数')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='分配时间')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='激活时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='分配过期时间')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('status', models.CharField(choices=[('active', '有效'), ('suspended', '已挂起'), ('revoked', '已撤销'), ('expired', '已过期'), ('pending', '待激活')], default='active', max_length=20, verbose_name='分配状态')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否主要分配')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='使用次数')),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True, verbose_name='最后心跳时间')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('revoke_reason', models.TextField(blank=True, verbose_name='撤销原因')),
                ('assignment_metadata', models.JSONField(blank=True, default=dict, verbose_name='分配元数据')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_licenses', to=settings.AUTH_USER_MODEL, verbose_name='分配操作员')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_assignments', to='licenses.license', verbose_name='分配许可证')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_assignments', to='users.member', verbose_name='分配成员')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_license_assignments', to=settings.AUTH_USER_MODEL, verbose_name='撤销操作员')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='关联租户')),
            ],
            options={
                'verbose_name': '许可证分配',
                'verbose_name_plural': '许可证分配',
                'db_table': 'licenses_license_assignment',
                'indexes': [models.Index(fields=['member', 'status'], name='la_member_status'), models.Index(fields=['license', 'status'], name='la_license_status'), models.Index(fields=['tenant', 'status'], name='la_tenant_status'), models.Index(fields=['tenant', 'member', 'status'], name='la_tenant_member'), models.Index(fields=['assigned_at'], name='la_assigned_at'), models.Index(condition=models.Q(('expires_at__isnull', False)), fields=['expires_at'], name='la_expires_at'), models.Index(fields=['is_primary', 'license'], name='la_primary'), models.Index(condition=models.Q(('last_used_at__isnull', False)), fields=['last_used_at'], name='la_last_used')],
                'constraints': [models.UniqueConstraint(fields=('member', 'license'), name='unique_member_license_assignment'), models.CheckConstraint(condition=models.Q(('max_devices_per_user__gte', 1)), name='valid_max_devices'), models.CheckConstraint(condition=models.Q(('usage_count__gte', 0)), name='valid_usage_count'), models.CheckConstraint(condition=models.Q(('expires_at__isnull', True), ('expires_at__gt', models.F('assigned_at')), _connector='OR'), name='valid_assignment_expiry')],
            },
        ),
    ]
