# Generated by Django 5.2 on 2026-01-15 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_remove_member_max_trial_licenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='WechatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(db_index=True, help_text='用户在当前小程序的唯一标识', max_length=64, unique=True, verbose_name='微信OpenID')),
                ('unionid', models.CharField(blank=True, db_index=True, help_text='用户在微信开放平台的唯一标识（跨应用互通时使用）', max_length=64, null=True, verbose_name='微信UnionID')),
                ('session_key', models.CharField(blank=True, help_text='微信会话密钥，用于解密用户数据，仅后端使用', max_length=128, null=True, verbose_name='会话密钥')),
                ('nickname', models.CharField(blank=True, max_length=64, null=True, verbose_name='微信昵称')),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='微信头像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('member', models.OneToOneField(help_text='绑定的系统会员账号', on_delete=django.db.models.deletion.CASCADE, related_name='wechat_user', to='users.member', verbose_name='关联会员')),
            ],
            options={
                'verbose_name': '微信用户',
                'verbose_name_plural': '微信用户',
                'db_table': 'wechat_user',
                'ordering': ['-created_at'],
            },
        ),
    ]
