# Generated by Django 5.2 on 2025-07-16 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('tenants', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('order_number', models.CharField(editable=False, max_length=100, unique=True, verbose_name='订单编号')),
                ('source_platform', models.CharField(blank=True, help_text='如：淘宝、小红书店铺、抖音私信等', max_length=100, null=True, verbose_name='来源平台')),
                ('project_manager', models.CharField(blank=True, help_text='如：三组、六组、九组等', max_length=100, null=True, verbose_name='项目负责人')),
                ('customer_type', models.CharField(blank=True, help_text='如：老客户、新客户、VIP客户等', max_length=100, null=True, verbose_name='客户类型')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='下单日期')),
                ('service_type', models.CharField(default='翻译', max_length=200, verbose_name='服务类型')),
                ('language', models.CharField(default='中英', max_length=100, verbose_name='语种')),
                ('customer_count', models.CharField(blank=True, help_text='如：份、字、天、半天、小时、页', max_length=100, null=True, verbose_name='客户数量')),
                ('translation_count', models.CharField(blank=True, help_text='与客户数量单位相同但单独计算', max_length=100, null=True, verbose_name='翻译数量')),
                ('service_time', models.DateField(blank=True, help_text='服务交付日期', null=True, verbose_name='服务时间')),
                ('project_location', models.CharField(blank=True, help_text='如：城市、线上', max_length=100, null=True, verbose_name='项目地点')),
                ('translator', models.CharField(blank=True, max_length=100, null=True, verbose_name='译员')),
                ('customer_price', models.CharField(blank=True, help_text='如：元/份、元/字、元/天、元/半天、元/小时、元/页', max_length=100, null=True, verbose_name='客户单价')),
                ('customer_total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='客户总价')),
                ('translator_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='译员费用')),
                ('translator_price', models.CharField(blank=True, help_text='如：元/份、元/字、元/天、元/半天、元/小时、元/页', max_length=100, null=True, verbose_name='翻译单价')),
                ('translator_payment_status', models.CharField(blank=True, help_text='如：已付款、未付款、月结30天', max_length=100, null=True, verbose_name='译费支付状态')),
                ('translator_payment_method', models.CharField(blank=True, help_text='如：对公转账、微信转账、支付宝转账', max_length=100, null=True, verbose_name='译费支付方式')),
                ('project_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='项目费用')),
                ('project_details', models.TextField(blank=True, null=True, verbose_name='项目明细')),
                ('cost_details', models.TextField(blank=True, null=True, verbose_name='费用明细')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='项目退款')),
                ('refund_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='退款原因')),
                ('payment_status', models.CharField(default='unpaid', max_length=50, verbose_name='支付状态')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='支付日期')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='支付方式')),
                ('payment_remarks', models.TextField(blank=True, null=True, verbose_name='支付备注')),
                ('invoice_status', models.CharField(default='not_required', max_length=50, verbose_name='发票状态')),
                ('invoice_info', models.TextField(blank=True, null=True, verbose_name='发票信息')),
                ('contract_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='合同编号')),
                ('contract_info', models.TextField(blank=True, null=True, verbose_name='合同信息')),
                ('contract_remarks', models.TextField(blank=True, null=True, verbose_name='合同备注')),
                ('delivery_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='收件地址')),
                ('order_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='订单地址')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('follow_up_record', models.TextField(blank=True, null=True, verbose_name='回访记录')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer', verbose_name='客户')),
                ('customer_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_contact_orders', to='users.member', verbose_name='客户联系人')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='版本号')),
                ('modified_at', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('change_details', models.TextField(default='{}', verbose_name='变更详情')),
                ('snapshot', models.TextField(default='{}', verbose_name='快照')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_modifications', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='orders.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单历史',
                'verbose_name_plural': '订单历史',
                'db_table': 'order_history',
                'ordering': ['-modified_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='order_order_n_06f120_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer'], name='order_custome_7c3d15_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderhistory',
            unique_together={('order', 'version')},
        ),
    ]
