# Generated by Django 5.2 on 2025-07-08 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_customermemberrelation_remarks_alter_customer_type_and_more'),
        ('tenants', '0004_delete_tenantbusinessinfo'),
        ('users', '0007_alter_member_options_alter_user_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('order_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='订单编号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待处理'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='订单状态')),
                ('service_type', models.CharField(choices=[('translation', '翻译'), ('interpretation', '口译'), ('proofreading', '校对'), ('typesetting', '排版'), ('localization', '本地化'), ('other', '其他')], max_length=20, verbose_name='服务类型')),
                ('language_direction', models.CharField(choices=[('zh-en', '中译英'), ('en-zh', '英译中'), ('zh-ja', '中译日'), ('ja-zh', '日译中'), ('zh-ko', '中译韩'), ('ko-zh', '韩译中'), ('en-ja', '英译日'), ('ja-en', '日译英'), ('en-ko', '英译韩'), ('ko-en', '韩译英'), ('other', '其他')], max_length=20, verbose_name='语言方向')),
                ('word_count', models.PositiveIntegerField(default=0, verbose_name='字数')),
                ('description', models.TextField(blank=True, null=True, verbose_name='项目描述')),
                ('translator_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='译员姓名')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='交付日期')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价(元/千字)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总金额')),
                ('translator_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='译员费用')),
                ('other_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='其他成本')),
                ('payment_status', models.CharField(choices=[('unpaid', '未支付'), ('partial', '部分支付'), ('paid', '已支付'), ('refunded', '已退款')], default='unpaid', max_length=20, verbose_name='支付状态')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='支付日期')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='支付方式')),
                ('payment_remarks', models.TextField(blank=True, null=True, verbose_name='支付备注')),
                ('invoice_status', models.CharField(choices=[('not_required', '不需要'), ('pending', '待开'), ('issued', '已开')], default='not_required', max_length=20, verbose_name='发票状态')),
                ('invoice_info', models.JSONField(blank=True, null=True, verbose_name='发票信息')),
                ('contract_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='合同编号')),
                ('contract_info', models.JSONField(blank=True, null=True, verbose_name='合同信息')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('attachments', models.JSONField(blank=True, null=True, verbose_name='附件列表')),
                ('tags', models.JSONField(blank=True, null=True, verbose_name='标签')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer', verbose_name='客户')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_orders', to=settings.AUTH_USER_MODEL, verbose_name='项目经理')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='租户')),
                ('translator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='translated_orders', to='users.member', verbose_name='译员')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='版本号')),
                ('modified_at', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('change_details', models.JSONField(default=dict, verbose_name='变更详情')),
                ('snapshot', models.JSONField(default=dict, verbose_name='快照')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_modifications', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='orders.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单历史',
                'verbose_name_plural': '订单历史',
                'db_table': 'order_history',
                'ordering': ['-modified_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='order_order_n_06f120_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer'], name='order_custome_7c3d15_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='order_status_35c31c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='order_payment_57a3c1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderhistory',
            unique_together={('order', 'version')},
        ),
    ]
