# Generated by Django 5.2 on 2025-07-08 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('users', '0007_alter_member_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='project_manager',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_contact_orders', to='users.member', verbose_name='客户联系人'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_status',
            field=models.CharField(default='not_required', max_length=50, verbose_name='发票状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='language_direction',
            field=models.CharField(max_length=50, verbose_name='语言方向'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='unpaid', max_length=50, verbose_name='支付状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_type',
            field=models.CharField(max_length=50, verbose_name='服务类型'),
        ),
        migrations.AlterField(
            model_name='order',
            name='translator',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='译员'),
        ),
    ]
