# Generated by Django 5.2 on 2025-07-08 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_project_manager_order_customer_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='translator_name',
        ),
    ]
