# Generated by Django 5.2 on 2025-07-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_translator_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='order',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='order',
            name='contract_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='合同备注'),
        ),
        migrations.AddField(
            model_name='order',
            name='follow_up_record',
            field=models.TextField(blank=True, null=True, verbose_name='回访记录'),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='单价'),
        ),
        migrations.AddField(
            model_name='order',
            name='project_details',
            field=models.TextField(blank=True, null=True, verbose_name='项目明细'),
        ),
        migrations.AddField(
            model_name='order',
            name='project_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='项目费用'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contract_info',
            field=models.TextField(blank=True, null=True, verbose_name='合同信息'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_info',
            field=models.TextField(blank=True, null=True, verbose_name='发票信息'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_type',
            field=models.CharField(max_length=200, verbose_name='服务类型'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tags',
            field=models.TextField(blank=True, null=True, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='change_details',
            field=models.TextField(default='{}', verbose_name='变更详情'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='snapshot',
            field=models.TextField(default='{}', verbose_name='快照'),
        ),
    ]
