# Generated by Django 5.2 on 2025-07-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_attachments_remove_order_unit_price_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='order_status_35c31c_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_payment_57a3c1_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='language_direction',
        ),
        migrations.RemoveField(
            model_name='order',
            name='other_costs',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='word_count',
        ),
        migrations.AddField(
            model_name='order',
            name='cost_details',
            field=models.TextField(blank=True, null=True, verbose_name='费用明细'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_count',
            field=models.CharField(blank=True, help_text='如：份、字、天、半天、小时、页', max_length=100, null=True, verbose_name='客户数量'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_price',
            field=models.CharField(blank=True, help_text='如：元/份、元/字、元/天、元/半天、元/小时、元/页', max_length=100, null=True, verbose_name='客户单价'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='客户总价'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_type',
            field=models.CharField(blank=True, help_text='如：老客户、新客户、VIP客户等', max_length=100, null=True, verbose_name='客户类型'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='收件地址'),
        ),
        migrations.AddField(
            model_name='order',
            name='language',
            field=models.CharField(default='中英', max_length=100, verbose_name='语种'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='下单地址'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='下单日期'),
        ),
        migrations.AddField(
            model_name='order',
            name='project_location',
            field=models.CharField(blank=True, help_text='如：城市、线上', max_length=100, null=True, verbose_name='项目地点'),
        ),
        migrations.AddField(
            model_name='order',
            name='project_manager',
            field=models.CharField(blank=True, help_text='如：三组、六组、九组等', max_length=100, null=True, verbose_name='项目负责人'),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='项目退款'),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_reason',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='退款原因'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_time',
            field=models.CharField(blank=True, help_text='如：笔译的约定交稿时间、口译的项目具体时间', max_length=200, null=True, verbose_name='服务时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='source_platform',
            field=models.CharField(blank=True, help_text='如：淘宝、小红书店铺、抖音私信等', max_length=100, null=True, verbose_name='来源平台'),
        ),
        migrations.AddField(
            model_name='order',
            name='translation_count',
            field=models.CharField(blank=True, help_text='与客户数量单位相同但单独计算', max_length=100, null=True, verbose_name='翻译数量'),
        ),
        migrations.AddField(
            model_name='order',
            name='translator_payment_method',
            field=models.CharField(blank=True, help_text='如：对公转账、微信转账、支付宝转账', max_length=100, null=True, verbose_name='译费支付方式'),
        ),
        migrations.AddField(
            model_name='order',
            name='translator_payment_status',
            field=models.CharField(blank=True, help_text='如：已付款、未付款、月结30天', max_length=100, null=True, verbose_name='译费支付状态'),
        ),
        migrations.AddField(
            model_name='order',
            name='translator_price',
            field=models.CharField(blank=True, help_text='如：元/份、元/字、元/天、元/半天、元/小时、元/页', max_length=100, null=True, verbose_name='翻译单价'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(editable=False, max_length=100, unique=True, verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_type',
            field=models.CharField(default='翻译', max_length=200, verbose_name='服务类型'),
        ),
    ]
