# Generated by Django 5.2 on 2025-07-12 10:33

from django.db import migrations, models
import datetime
import re

def convert_service_time(apps, schema_editor):
    """
    将service_time字段从字符串格式转换为日期格式
    尝试从字符串中提取日期信息
    """
    Order = apps.get_model('orders', 'Order')
    # 提取日期的正则表达式
    date_pattern = re.compile(r'(\d{4})-(\d{1,2})-(\d{1,2})')
    
    for order in Order.objects.all():
        if not order.service_time:
            continue
            
        # 尝试从service_time中提取日期
        match = date_pattern.search(order.service_time)
        if match:
            # 如果找到日期格式，直接使用
            try:
                year = int(match.group(1))
                month = int(match.group(2))
                day = int(match.group(3))
                order.service_time = datetime.date(year, month, day)
                order.save(update_fields=['service_time'])
            except (ValueError, OverflowError):
                # 如果日期值无效，设为NULL
                order.service_time = None
                order.save(update_fields=['service_time'])
        else:
            # 如果没有找到日期格式，设为NULL
            order.service_time = None
            order.save(update_fields=['service_time'])

def reverse_convert_service_time(apps, schema_editor):
    """
    将service_time字段从日期格式转回字符串格式
    """
    # 反向操作，但实际上无法恢复原始格式，只能保留日期
    Order = apps.get_model('orders', 'Order')
    for order in Order.objects.all():
        if order.service_time:
            # 将日期转换为字符串格式
            order.service_time = order.service_time.strftime('%Y-%m-%d')
            order.save(update_fields=['service_time'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_order_status_35c31c_idx_and_more'),
    ]
    
    # 先转换service_time字段的数据类型
    operations = [
        # 第一步：先添加一个临时字段
        migrations.AddField(
            model_name='order',
            name='temp_service_time',
            field=models.DateField(blank=True, null=True),
        ),
        
        # 第二步：运行数据转换函数
        migrations.RunPython(
            code=convert_service_time,
            reverse_code=reverse_convert_service_time,
        ),
        
        # 第三步：移除旧字段
        migrations.RemoveField(
            model_name='order',
            name='service_time',
        ),
        
        # 第四步：重命名临时字段
        migrations.RenameField(
            model_name='order',
            old_name='temp_service_time',
            new_name='service_time',
        ),
        
        # 第五步：设置新字段的属性
        migrations.AlterField(
            model_name='order',
            name='service_time',
            field=models.DateField(blank=True, help_text='服务交付日期', null=True, verbose_name='服务时间'),
        ),
        
        # 其他字段的修改
        migrations.AlterField(
            model_name='order',
            name='order_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='订单地址'),
        ),
    ]
