# Generated by Django 5.2 on 2026-01-08 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0004_alter_application_logo'),
        ('tenants', '0002_alter_tenantquota_current_storage_used_mb'),
        ('users', '0004_remove_member_max_trial_licenses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('scope', models.CharField(choices=[('tenant', '面向租户'), ('application', '面向应用'), ('members', '面向特定成员')], db_index=True, default='tenant', help_text='tenant=租户下所有成员, application=关联应用, members=指定成员', max_length=20, verbose_name='通知范围')),
                ('title', models.CharField(max_length=200, verbose_name='通知标题')),
                ('content', models.TextField(help_text='支持富文本/Markdown', verbose_name='通知内容')),
                ('notification_type', models.CharField(choices=[('info', '信息通知'), ('warning', '警告通知'), ('error', '错误通知'), ('update', '更新通知'), ('announcement', '公告')], db_index=True, default='info', max_length=20, verbose_name='通知类型')),
                ('priority', models.CharField(choices=[('low', '低'), ('normal', '普通'), ('high', '高'), ('urgent', '紧急')], db_index=True, default='normal', max_length=20, verbose_name='优先级')),
                ('send_email', models.BooleanField(default=False, help_text='发布时是否同时发送邮件通知', verbose_name='是否发送邮件')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='邮件发送时间')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], db_index=True, default='draft', max_length=20, verbose_name='状态')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('application', models.ForeignKey(blank=True, help_text='仅当 scope=application 时需要填写', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='applications.application', verbose_name='关联应用')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='是否已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipients', to='users.member', verbose_name='成员')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='notifications.notification', verbose_name='通知')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '通知接收者',
                'verbose_name_plural': '通知接收者',
                'db_table': 'notification_recipient',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant', 'scope'], name='notificatio_tenant__01b587_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant', 'application'], name='notificatio_tenant__1db552_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant', 'status'], name='notificatio_tenant__710c83_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant', 'created_at'], name='notificatio_tenant__60fb10_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrecipient',
            index=models.Index(fields=['member', 'is_read'], name='notificatio_member__bc11c6_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrecipient',
            index=models.Index(fields=['notification', 'is_read'], name='notificatio_notific_cc062a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationrecipient',
            unique_together={('notification', 'member')},
        ),
    ]
